// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/primait/pulumi-launchdarkly/sdk/go/launchdarkly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The [personal access token](https://launchdarkly.com/docs/home/account/api#personal-tokens) or [service token](https://launchdarkly.com/docs/home/account/api#service-tokens) used to authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_ACCESS_TOKEN` environment variable. You must provide either `accessToken` or `oauthToken`.
func GetAccess_token(ctx *pulumi.Context) string {
	return config.Get(ctx, "launchdarkly:access_token")
}

// The LaunchDarkly host address. If this argument is not specified, the default host address is `https://app.launchdarkly.com`
func GetApi_host(ctx *pulumi.Context) string {
	return config.Get(ctx, "launchdarkly:api_host")
}

// When `true`, removing a `FeatureFlag` resource from your Terraform configuration archives the flag in LaunchDarkly instead of deleting it. The flag's key is retained on the server, so re-applying a configuration that recreates the same flag key will fail with an error directing you to `terraform import` the archived flag. Defaults to `false`, which preserves the existing destroy-deletes behavior. This setting affects only `FeatureFlag`. Other resources continue to be deleted on destroy.
func GetArchiveFlagsOnDestroy(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "launchdarkly:archiveFlagsOnDestroy")
}

// The HTTP timeout (in seconds) when making API calls to LaunchDarkly. Defaults to 20 seconds.
func GetHttp_timeout(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "launchdarkly:http_timeout")
}

// The maximum number of concurrent API requests the provider makes to LaunchDarkly. Defaults to `1`. Increase this value to speed up plan and refresh operations on large configurations. Higher values make it more likely that requests exceed your account's API rate limit. If a request exceeds the rate limit, LaunchDarkly returns a `429` response and the provider retries the request automatically.
func GetMaxConcurrency(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "launchdarkly:maxConcurrency")
}

// An OAuth V2 token you use to authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_OAUTH_TOKEN` environment variable. You must provide either `accessToken` or `oauthToken`.
func GetOauth_token(ctx *pulumi.Context) string {
	return config.Get(ctx, "launchdarkly:oauth_token")
}
