version: 2
updates:
- package-ecosystem: docker
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  commit-message:
    prefix: "chore(deps-docker)"
  directories:
  - '*'
  groups:
    docker-non-major:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
- package-ecosystem: github-actions
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  commit-message:
    prefix: "chore(deps-github-actions)"
  directory: /
  groups:
    github-actions-non-major:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
- package-ecosystem: gomod
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  commit-message:
    prefix: "chore(deps-gomod)"
  directories:
  - '*'
  groups:
    gomod-non-major:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
- package-ecosystem: npm
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  commit-message:
    prefix: "chore(deps-npm)"
  directories:
  - '*'
  groups:
    npm-non-major:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
- package-ecosystem: nuget
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  commit-message:
    prefix: "chore(deps-nuget)"
  directories:
  - '*'
  groups:
    nuget-non-major:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
- package-ecosystem: pip
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  commit-message:
    prefix: "chore(deps-pip)"
  directories:
  - '*'
  groups:
    pip-non-major:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
