// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Launchdarkly
{
    /// <summary>
    /// Provides a LaunchDarkly AI tool resource.
    /// 
    /// This resource allows you to create and manage AI tools within your LaunchDarkly project.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using System.Text.Json;
    /// using Pulumi;
    /// using Launchdarkly = Pulumi.Launchdarkly;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Launchdarkly.Index.AiTool("example", new()
    ///     {
    ///         ProjectKey = exampleLaunchdarklyProject.Key,
    ///         Key = "web-search",
    ///         Description = "Search the web for information",
    ///         SchemaJson = JsonSerializer.Serialize(new Dictionary&lt;string, object?&gt;
    ///         {
    ///             ["type"] = "object",
    ///             ["properties"] = new Dictionary&lt;string, object?&gt;
    ///             {
    ///                 ["query"] = new Dictionary&lt;string, object?&gt;
    ///                 {
    ///                     ["type"] = "string",
    ///                     ["description"] = "The search query",
    ///                 },
    ///             },
    ///             ["required"] = new[]
    ///             {
    ///                 "query",
    ///             },
    ///         }),
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// LaunchDarkly AI tools can be imported using the format `project_key/tool_key`
    /// 
    /// ```sh
    /// $ pulumi import launchdarkly:index/aiTool:AiTool example example-project/web-search
    /// ```
    /// </summary>
    [LaunchdarklyResourceType("launchdarkly:index/aiTool:AiTool")]
    public partial class AiTool : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The creation timestamp of the AI tool.
        /// </summary>
        [Output("creationDate")]
        public Output<int> CreationDate { get; private set; } = null!;

        /// <summary>
        /// A JSON string representing custom application-level metadata for the AI tool.
        /// </summary>
        [Output("customParameters")]
        public Output<string?> CustomParameters { get; private set; } = null!;

        /// <summary>
        /// The AI tool's description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The AI tool's unique key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// The member ID of the maintainer for this AI tool. Conflicts with `MaintainerTeamKey`.
        /// </summary>
        [Output("maintainerId")]
        public Output<string> MaintainerId { get; private set; } = null!;

        /// <summary>
        /// The team key of the maintainer team for this AI tool. Conflicts with `MaintainerId`.
        /// </summary>
        [Output("maintainerTeamKey")]
        public Output<string> MaintainerTeamKey { get; private set; } = null!;

        /// <summary>
        /// The project key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Output("projectKey")]
        public Output<string> ProjectKey { get; private set; } = null!;

        /// <summary>
        /// A JSON string representing the JSON Schema for the tool's parameters.
        /// </summary>
        [Output("schemaJson")]
        public Output<string> SchemaJson { get; private set; } = null!;

        /// <summary>
        /// The version of the AI tool.
        /// </summary>
        [Output("version")]
        public Output<int> Version { get; private set; } = null!;


        /// <summary>
        /// Create a AiTool resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AiTool(string name, AiToolArgs args, CustomResourceOptions? options = null)
            : base("launchdarkly:index/aiTool:AiTool", name, args ?? new AiToolArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AiTool(string name, Input<string> id, AiToolState? state = null, CustomResourceOptions? options = null)
            : base("launchdarkly:index/aiTool:AiTool", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/primait/pulumi-launchdarkly",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AiTool resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AiTool Get(string name, Input<string> id, AiToolState? state = null, CustomResourceOptions? options = null)
        {
            return new AiTool(name, id, state, options);
        }
    }

    public sealed class AiToolArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A JSON string representing custom application-level metadata for the AI tool.
        /// </summary>
        [Input("customParameters")]
        public Input<string>? CustomParameters { get; set; }

        /// <summary>
        /// The AI tool's description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The AI tool's unique key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The member ID of the maintainer for this AI tool. Conflicts with `MaintainerTeamKey`.
        /// </summary>
        [Input("maintainerId")]
        public Input<string>? MaintainerId { get; set; }

        /// <summary>
        /// The team key of the maintainer team for this AI tool. Conflicts with `MaintainerId`.
        /// </summary>
        [Input("maintainerTeamKey")]
        public Input<string>? MaintainerTeamKey { get; set; }

        /// <summary>
        /// The project key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Input("projectKey", required: true)]
        public Input<string> ProjectKey { get; set; } = null!;

        /// <summary>
        /// A JSON string representing the JSON Schema for the tool's parameters.
        /// </summary>
        [Input("schemaJson", required: true)]
        public Input<string> SchemaJson { get; set; } = null!;

        public AiToolArgs()
        {
        }
        public static new AiToolArgs Empty => new AiToolArgs();
    }

    public sealed class AiToolState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The creation timestamp of the AI tool.
        /// </summary>
        [Input("creationDate")]
        public Input<int>? CreationDate { get; set; }

        /// <summary>
        /// A JSON string representing custom application-level metadata for the AI tool.
        /// </summary>
        [Input("customParameters")]
        public Input<string>? CustomParameters { get; set; }

        /// <summary>
        /// The AI tool's description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The AI tool's unique key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// The member ID of the maintainer for this AI tool. Conflicts with `MaintainerTeamKey`.
        /// </summary>
        [Input("maintainerId")]
        public Input<string>? MaintainerId { get; set; }

        /// <summary>
        /// The team key of the maintainer team for this AI tool. Conflicts with `MaintainerId`.
        /// </summary>
        [Input("maintainerTeamKey")]
        public Input<string>? MaintainerTeamKey { get; set; }

        /// <summary>
        /// The project key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Input("projectKey")]
        public Input<string>? ProjectKey { get; set; }

        /// <summary>
        /// A JSON string representing the JSON Schema for the tool's parameters.
        /// </summary>
        [Input("schemaJson")]
        public Input<string>? SchemaJson { get; set; }

        /// <summary>
        /// The version of the AI tool.
        /// </summary>
        [Input("version")]
        public Input<int>? Version { get; set; }

        public AiToolState()
        {
        }
        public static new AiToolState Empty => new AiToolState();
    }
}
