// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Launchdarkly
{
    public static class GetView
    {
        /// <summary>
        /// Provides a LaunchDarkly view data source.
        /// 
        /// This data source allows you to retrieve view information from your LaunchDarkly project.
        /// </summary>
        public static Task<GetViewResult> InvokeAsync(GetViewArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetViewResult>("launchdarkly:index/getView:getView", args ?? new GetViewArgs(), options.WithDefaults());

        /// <summary>
        /// Provides a LaunchDarkly view data source.
        /// 
        /// This data source allows you to retrieve view information from your LaunchDarkly project.
        /// </summary>
        public static Output<GetViewResult> Invoke(GetViewInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetViewResult>("launchdarkly:index/getView:getView", args ?? new GetViewInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Provides a LaunchDarkly view data source.
        /// 
        /// This data source allows you to retrieve view information from your LaunchDarkly project.
        /// </summary>
        public static Output<GetViewResult> Invoke(GetViewInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetViewResult>("launchdarkly:index/getView:getView", args ?? new GetViewInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetViewArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The view's unique key. Must be lowercase. LaunchDarkly normalizes view keys to lowercase.
        /// </summary>
        [Input("key", required: true)]
        public string Key { get; set; } = null!;

        /// <summary>
        /// The project key.
        /// </summary>
        [Input("projectKey", required: true)]
        public string ProjectKey { get; set; } = null!;

        public GetViewArgs()
        {
        }
        public static new GetViewArgs Empty => new GetViewArgs();
    }

    public sealed class GetViewInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The view's unique key. Must be lowercase. LaunchDarkly normalizes view keys to lowercase.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The project key.
        /// </summary>
        [Input("projectKey", required: true)]
        public Input<string> ProjectKey { get; set; } = null!;

        public GetViewInvokeArgs()
        {
        }
        public static new GetViewInvokeArgs Empty => new GetViewInvokeArgs();
    }


    [OutputType]
    public sealed class GetViewResult
    {
        /// <summary>
        /// The view's description.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// View ID.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The view's unique key. Must be lowercase. LaunchDarkly normalizes view keys to lowercase.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// Feature flag keys linked to this view.
        /// </summary>
        public readonly ImmutableArray<string> LinkedFlags;
        /// <summary>
        /// Segments linked to this view.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetViewLinkedSegmentResult> LinkedSegments;
        /// <summary>
        /// Member ID of the maintainer.
        /// </summary>
        public readonly string MaintainerId;
        /// <summary>
        /// Team key of the maintainer team.
        /// </summary>
        public readonly string MaintainerTeamKey;
        /// <summary>
        /// The view's name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The project key.
        /// </summary>
        public readonly string ProjectKey;
        /// <summary>
        /// Tags.
        /// </summary>
        public readonly ImmutableArray<string> Tags;

        [OutputConstructor]
        private GetViewResult(
            string description,

            string id,

            string key,

            ImmutableArray<string> linkedFlags,

            ImmutableArray<Outputs.GetViewLinkedSegmentResult> linkedSegments,

            string maintainerId,

            string maintainerTeamKey,

            string name,

            string projectKey,

            ImmutableArray<string> tags)
        {
            Description = description;
            Id = id;
            Key = key;
            LinkedFlags = linkedFlags;
            LinkedSegments = linkedSegments;
            MaintainerId = maintainerId;
            MaintainerTeamKey = maintainerTeamKey;
            Name = name;
            ProjectKey = projectKey;
            Tags = tags;
        }
    }
}
