// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Launchdarkly
{
    /// <summary>
    /// Provides a LaunchDarkly project resource.
    /// 
    /// This resource allows you to create and manage projects within your LaunchDarkly organization.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Launchdarkly = Pulumi.Launchdarkly;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Launchdarkly.Project("example", new()
    ///     {
    ///         Key = "example-project",
    ///         Name = "Example project",
    ///         Tags = new[]
    ///         {
    ///             "terraform",
    ///         },
    ///         RequireViewAssociationForNewFlags = false,
    ///         RequireViewAssociationForNewSegments = false,
    ///         Environments = 
    ///         {
    ///             { "production", new Launchdarkly.Inputs.ProjectEnvironmentsArgs
    ///             {
    ///                 Key = "production",
    ///                 Name = "Production",
    ///                 Color = "EEEEEE",
    ///                 Tags = new[]
    ///                 {
    ///                     "terraform",
    ///                 },
    ///                 ApprovalSettings = new Launchdarkly.Inputs.ProjectEnvironmentsApprovalSettingsArgs
    ///                 {
    ///                     CanReviewOwnRequest = false,
    ///                     CanApplyDeclinedChanges = false,
    ///                     MinNumApprovals = 3,
    ///                     RequiredApprovalTags = new[]
    ///                     {
    ///                         "approvals_required",
    ///                     },
    ///                 },
    ///             } },
    ///             { "staging", new Launchdarkly.Inputs.ProjectEnvironmentsArgs
    ///             {
    ///                 Key = "staging",
    ///                 Name = "Staging",
    ///                 Color = "000000",
    ///                 Tags = new[]
    ///                 {
    ///                     "terraform",
    ///                 },
    ///             } },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// LaunchDarkly projects can be imported using the project's key.
    /// 
    /// ```sh
    /// $ pulumi import launchdarkly:index/project:Project example example-project
    /// ```
    /// 
    /// **IMPORTANT:** On import, Terraform saves _all_ of the project's environments to state, keyed by their environment `Key`. `Environments` is authoritative: on a subsequent apply, any environment that is in state but absent from your configuration is **deleted**, along with its SDK keys and all flag targeting. To manage the project in Terraform but leave its environments to the LaunchDarkly UI, or to [`launchdarkly.Environment`](https://www.terraform.io/docs/providers/launchdarkly/r/environment.html) resources, declare your environments and use Terraform's ignore changes lifecycle meta-argument:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Launchdarkly = Pulumi.Launchdarkly;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Launchdarkly.Project("example", new()
    ///     {
    ///         Name = "testProject",
    ///         Key = "example-project",
    ///         Environments = 
    ///         {
    ///             { "production", new Launchdarkly.Inputs.ProjectEnvironmentsArgs
    ///             {
    ///                 Key = "production",
    ///                 Name = "Production",
    ///                 Color = "EEEEEE",
    ///             } },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// Because `Environments` is a map keyed by environment `Key`, reordering, adding, or removing one environment never forces changes to the others, and import is order-independent. Changing an environment's key, which is the map key, deletes the old environment and creates a new one.
    /// 
    /// **Managing environment resources with Terraform should always be done on the project unless the project is not also managed with Terraform.**
    /// </summary>
    [LaunchdarklyResourceType("launchdarkly:index/project:Project")]
    public partial class Project : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Which client-side SDKs can use new flags by default.
        /// </summary>
        [Output("defaultClientSideAvailability")]
        public Output<Outputs.ProjectDefaultClientSideAvailability?> DefaultClientSideAvailability { get; private set; } = null!;

        /// <summary>
        /// Map of environments that belong to the project, keyed by environment `Key`. This is the complete, authoritative set of the project's environments: any environment not present in the map is deleted on apply. Reordering, adding, or removing one environment does not affect the others. A project must have at least one environment.
        /// 
        /// &gt; **Warning:** Changing an environment's key, which is the map key, deletes that environment, including its SDK keys and all of its flag targeting, and creates a new one. This is irreversible.
        /// 
        /// To manage the project in Terraform but manage its environments elsewhere, such as in the LaunchDarkly UI or with [`launchdarkly.Environment`](https://www.terraform.io/docs/providers/launchdarkly/r/environment.html) resources, declare your initial environments and add `lifecycle { IgnoreChanges = [environments] }`.
        /// 
        /// &gt; **Note:** Mixing the use of nested `Environments` and `launchdarkly.Environment` resources for the same project is not recommended. `launchdarkly.Environment` resources should be used together with `IgnoreChanges` on the project's `Environments`, or when the encapsulating project is not managed in Terraform.
        /// </summary>
        [Output("environments")]
        public Output<ImmutableDictionary<string, Outputs.ProjectEnvironments>> Environments { get; private set; } = null!;

        /// <summary>
        /// The project's unique key. A change in this field forces the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// The project's name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Whether new flags created in this project must be associated with at least one view.
        /// </summary>
        [Output("requireViewAssociationForNewFlags")]
        public Output<bool> RequireViewAssociationForNewFlags { get; private set; } = null!;

        /// <summary>
        /// Whether new segments created in this project must be associated with at least one view.
        /// </summary>
        [Output("requireViewAssociationForNewSegments")]
        public Output<bool> RequireViewAssociationForNewSegments { get; private set; } = null!;

        /// <summary>
        /// Tags associated with your resource.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;


        /// <summary>
        /// Create a Project resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Project(string name, ProjectArgs args, CustomResourceOptions? options = null)
            : base("launchdarkly:index/project:Project", name, args ?? new ProjectArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Project(string name, Input<string> id, ProjectState? state = null, CustomResourceOptions? options = null)
            : base("launchdarkly:index/project:Project", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/primait/pulumi-launchdarkly",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Project resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Project Get(string name, Input<string> id, ProjectState? state = null, CustomResourceOptions? options = null)
        {
            return new Project(name, id, state, options);
        }
    }

    public sealed class ProjectArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Which client-side SDKs can use new flags by default.
        /// </summary>
        [Input("defaultClientSideAvailability")]
        public Input<Inputs.ProjectDefaultClientSideAvailabilityArgs>? DefaultClientSideAvailability { get; set; }

        [Input("environments", required: true)]
        private InputMap<Inputs.ProjectEnvironmentsArgs>? _environments;

        /// <summary>
        /// Map of environments that belong to the project, keyed by environment `Key`. This is the complete, authoritative set of the project's environments: any environment not present in the map is deleted on apply. Reordering, adding, or removing one environment does not affect the others. A project must have at least one environment.
        /// 
        /// &gt; **Warning:** Changing an environment's key, which is the map key, deletes that environment, including its SDK keys and all of its flag targeting, and creates a new one. This is irreversible.
        /// 
        /// To manage the project in Terraform but manage its environments elsewhere, such as in the LaunchDarkly UI or with [`launchdarkly.Environment`](https://www.terraform.io/docs/providers/launchdarkly/r/environment.html) resources, declare your initial environments and add `lifecycle { IgnoreChanges = [environments] }`.
        /// 
        /// &gt; **Note:** Mixing the use of nested `Environments` and `launchdarkly.Environment` resources for the same project is not recommended. `launchdarkly.Environment` resources should be used together with `IgnoreChanges` on the project's `Environments`, or when the encapsulating project is not managed in Terraform.
        /// </summary>
        public InputMap<Inputs.ProjectEnvironmentsArgs> Environments
        {
            get => _environments ?? (_environments = new InputMap<Inputs.ProjectEnvironmentsArgs>());
            set => _environments = value;
        }

        /// <summary>
        /// The project's unique key. A change in this field forces the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The project's name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Whether new flags created in this project must be associated with at least one view.
        /// </summary>
        [Input("requireViewAssociationForNewFlags")]
        public Input<bool>? RequireViewAssociationForNewFlags { get; set; }

        /// <summary>
        /// Whether new segments created in this project must be associated with at least one view.
        /// </summary>
        [Input("requireViewAssociationForNewSegments")]
        public Input<bool>? RequireViewAssociationForNewSegments { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Tags associated with your resource.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public ProjectArgs()
        {
        }
        public static new ProjectArgs Empty => new ProjectArgs();
    }

    public sealed class ProjectState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Which client-side SDKs can use new flags by default.
        /// </summary>
        [Input("defaultClientSideAvailability")]
        public Input<Inputs.ProjectDefaultClientSideAvailabilityGetArgs>? DefaultClientSideAvailability { get; set; }

        [Input("environments")]
        private InputMap<Inputs.ProjectEnvironmentsGetArgs>? _environments;

        /// <summary>
        /// Map of environments that belong to the project, keyed by environment `Key`. This is the complete, authoritative set of the project's environments: any environment not present in the map is deleted on apply. Reordering, adding, or removing one environment does not affect the others. A project must have at least one environment.
        /// 
        /// &gt; **Warning:** Changing an environment's key, which is the map key, deletes that environment, including its SDK keys and all of its flag targeting, and creates a new one. This is irreversible.
        /// 
        /// To manage the project in Terraform but manage its environments elsewhere, such as in the LaunchDarkly UI or with [`launchdarkly.Environment`](https://www.terraform.io/docs/providers/launchdarkly/r/environment.html) resources, declare your initial environments and add `lifecycle { IgnoreChanges = [environments] }`.
        /// 
        /// &gt; **Note:** Mixing the use of nested `Environments` and `launchdarkly.Environment` resources for the same project is not recommended. `launchdarkly.Environment` resources should be used together with `IgnoreChanges` on the project's `Environments`, or when the encapsulating project is not managed in Terraform.
        /// </summary>
        public InputMap<Inputs.ProjectEnvironmentsGetArgs> Environments
        {
            get => _environments ?? (_environments = new InputMap<Inputs.ProjectEnvironmentsGetArgs>());
            set => _environments = value;
        }

        /// <summary>
        /// The project's unique key. A change in this field forces the destruction of the existing resource and the creation of a new one.
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// The project's name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Whether new flags created in this project must be associated with at least one view.
        /// </summary>
        [Input("requireViewAssociationForNewFlags")]
        public Input<bool>? RequireViewAssociationForNewFlags { get; set; }

        /// <summary>
        /// Whether new segments created in this project must be associated with at least one view.
        /// </summary>
        [Input("requireViewAssociationForNewSegments")]
        public Input<bool>? RequireViewAssociationForNewSegments { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Tags associated with your resource.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public ProjectState()
        {
        }
        public static new ProjectState Empty => new ProjectState();
    }
}
