// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package launchdarkly

import (
	"context"
	"reflect"

	"errors"
	"github.com/primait/pulumi-launchdarkly/sdk/go/launchdarkly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides a LaunchDarkly flag import configuration resource.
//
// > **Beta:** This resource wraps a beta LaunchDarkly API. Beta resources may change or be removed in future versions.
//
// This resource lets you create and manage flag import configurations, which import feature flags from an external feature management system (identified by `integrationKey`, for example `split`) into a LaunchDarkly project. The shape of `config` varies by integration and is described by the `formVariables` in that integration's manifest. To learn more, read [Importing flags from another provider](https://launchdarkly.com/docs/home/flags/import).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"encoding/json"
//
//	"github.com/primait/pulumi-launchdarkly/sdk/go/launchdarkly"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			tmpJSON0, err := json.Marshal(map[string]interface{}{
//				"workspaceApiKey": splitWorkspaceApiKey,
//				"workspaceId":     splitWorkspaceId,
//				"environmentId":   splitEnvironmentId,
//				"ldApiKey":        launchdarklyApiKey,
//			})
//			if err != nil {
//				return err
//			}
//			json0 := string(tmpJSON0)
//			_, err = launchdarkly.NewFlagImportConfiguration(ctx, "split_import", &launchdarkly.FlagImportConfigurationArgs{
//				ProjectKey:     pulumi.Any(example.Key),
//				IntegrationKey: pulumi.String("split"),
//				Name:           pulumi.String("Split flag import"),
//				Config:         pulumi.String(json0),
//				Tags: pulumi.StringArray{
//					pulumi.String("imported"),
//					pulumi.String("split"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// A flag import configuration can be imported using the composite ID in the format
// `project_key/integration_key/integration_id`.
//
// ```sh
// $ pulumi import launchdarkly:index/flagImportConfiguration:FlagImportConfiguration split_import example-project/split/57c12345abcd1234ef567890
// ```
type FlagImportConfiguration struct {
	pulumi.CustomResourceState

	// A JSON-encoded object of configuration values for the integration. The accepted keys vary by `integrationKey` and are described by the `formVariables` in the integration's manifest (often including a secret API token). Marked sensitive because it commonly contains credentials.
	Config pulumi.StringOutput `pulumi:"config"`
	// The unique identifier the LaunchDarkly API assigns to this flag import configuration.
	IntegrationId pulumi.StringOutput `pulumi:"integrationId"`
	// The integration key identifying the external feature management system to import flags from, for example `split`. A change in this field forces the destruction of the existing resource and the creation of a new one.
	IntegrationKey pulumi.StringOutput `pulumi:"integrationKey"`
	// A human-friendly name for the flag import configuration. If not set, the LaunchDarkly API assigns a default.
	Name pulumi.StringOutput `pulumi:"name"`
	// The key of the project to import flags into. A change in this field forces the destruction of the existing resource and the creation of a new one.
	ProjectKey pulumi.StringOutput `pulumi:"projectKey"`
	// Tags associated with the flag import configuration.
	Tags pulumi.StringArrayOutput `pulumi:"tags"`
	// The version of the flag import configuration.
	Version pulumi.IntOutput `pulumi:"version"`
}

// NewFlagImportConfiguration registers a new resource with the given unique name, arguments, and options.
func NewFlagImportConfiguration(ctx *pulumi.Context,
	name string, args *FlagImportConfigurationArgs, opts ...pulumi.ResourceOption) (*FlagImportConfiguration, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Config == nil {
		return nil, errors.New("invalid value for required argument 'Config'")
	}
	if args.IntegrationKey == nil {
		return nil, errors.New("invalid value for required argument 'IntegrationKey'")
	}
	if args.ProjectKey == nil {
		return nil, errors.New("invalid value for required argument 'ProjectKey'")
	}
	if args.Config != nil {
		args.Config = pulumi.ToSecret(args.Config).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"config",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource FlagImportConfiguration
	err := ctx.RegisterResource("launchdarkly:index/flagImportConfiguration:FlagImportConfiguration", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFlagImportConfiguration gets an existing FlagImportConfiguration resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFlagImportConfiguration(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FlagImportConfigurationState, opts ...pulumi.ResourceOption) (*FlagImportConfiguration, error) {
	var resource FlagImportConfiguration
	err := ctx.ReadResource("launchdarkly:index/flagImportConfiguration:FlagImportConfiguration", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FlagImportConfiguration resources.
type flagImportConfigurationState struct {
	// A JSON-encoded object of configuration values for the integration. The accepted keys vary by `integrationKey` and are described by the `formVariables` in the integration's manifest (often including a secret API token). Marked sensitive because it commonly contains credentials.
	Config *string `pulumi:"config"`
	// The unique identifier the LaunchDarkly API assigns to this flag import configuration.
	IntegrationId *string `pulumi:"integrationId"`
	// The integration key identifying the external feature management system to import flags from, for example `split`. A change in this field forces the destruction of the existing resource and the creation of a new one.
	IntegrationKey *string `pulumi:"integrationKey"`
	// A human-friendly name for the flag import configuration. If not set, the LaunchDarkly API assigns a default.
	Name *string `pulumi:"name"`
	// The key of the project to import flags into. A change in this field forces the destruction of the existing resource and the creation of a new one.
	ProjectKey *string `pulumi:"projectKey"`
	// Tags associated with the flag import configuration.
	Tags []string `pulumi:"tags"`
	// The version of the flag import configuration.
	Version *int `pulumi:"version"`
}

type FlagImportConfigurationState struct {
	// A JSON-encoded object of configuration values for the integration. The accepted keys vary by `integrationKey` and are described by the `formVariables` in the integration's manifest (often including a secret API token). Marked sensitive because it commonly contains credentials.
	Config pulumi.StringPtrInput
	// The unique identifier the LaunchDarkly API assigns to this flag import configuration.
	IntegrationId pulumi.StringPtrInput
	// The integration key identifying the external feature management system to import flags from, for example `split`. A change in this field forces the destruction of the existing resource and the creation of a new one.
	IntegrationKey pulumi.StringPtrInput
	// A human-friendly name for the flag import configuration. If not set, the LaunchDarkly API assigns a default.
	Name pulumi.StringPtrInput
	// The key of the project to import flags into. A change in this field forces the destruction of the existing resource and the creation of a new one.
	ProjectKey pulumi.StringPtrInput
	// Tags associated with the flag import configuration.
	Tags pulumi.StringArrayInput
	// The version of the flag import configuration.
	Version pulumi.IntPtrInput
}

func (FlagImportConfigurationState) ElementType() reflect.Type {
	return reflect.TypeOf((*flagImportConfigurationState)(nil)).Elem()
}

type flagImportConfigurationArgs struct {
	// A JSON-encoded object of configuration values for the integration. The accepted keys vary by `integrationKey` and are described by the `formVariables` in the integration's manifest (often including a secret API token). Marked sensitive because it commonly contains credentials.
	Config string `pulumi:"config"`
	// The integration key identifying the external feature management system to import flags from, for example `split`. A change in this field forces the destruction of the existing resource and the creation of a new one.
	IntegrationKey string `pulumi:"integrationKey"`
	// A human-friendly name for the flag import configuration. If not set, the LaunchDarkly API assigns a default.
	Name *string `pulumi:"name"`
	// The key of the project to import flags into. A change in this field forces the destruction of the existing resource and the creation of a new one.
	ProjectKey string `pulumi:"projectKey"`
	// Tags associated with the flag import configuration.
	Tags []string `pulumi:"tags"`
}

// The set of arguments for constructing a FlagImportConfiguration resource.
type FlagImportConfigurationArgs struct {
	// A JSON-encoded object of configuration values for the integration. The accepted keys vary by `integrationKey` and are described by the `formVariables` in the integration's manifest (often including a secret API token). Marked sensitive because it commonly contains credentials.
	Config pulumi.StringInput
	// The integration key identifying the external feature management system to import flags from, for example `split`. A change in this field forces the destruction of the existing resource and the creation of a new one.
	IntegrationKey pulumi.StringInput
	// A human-friendly name for the flag import configuration. If not set, the LaunchDarkly API assigns a default.
	Name pulumi.StringPtrInput
	// The key of the project to import flags into. A change in this field forces the destruction of the existing resource and the creation of a new one.
	ProjectKey pulumi.StringInput
	// Tags associated with the flag import configuration.
	Tags pulumi.StringArrayInput
}

func (FlagImportConfigurationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*flagImportConfigurationArgs)(nil)).Elem()
}

type FlagImportConfigurationInput interface {
	pulumi.Input

	ToFlagImportConfigurationOutput() FlagImportConfigurationOutput
	ToFlagImportConfigurationOutputWithContext(ctx context.Context) FlagImportConfigurationOutput
}

func (*FlagImportConfiguration) ElementType() reflect.Type {
	return reflect.TypeOf((**FlagImportConfiguration)(nil)).Elem()
}

func (i *FlagImportConfiguration) ToFlagImportConfigurationOutput() FlagImportConfigurationOutput {
	return i.ToFlagImportConfigurationOutputWithContext(context.Background())
}

func (i *FlagImportConfiguration) ToFlagImportConfigurationOutputWithContext(ctx context.Context) FlagImportConfigurationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FlagImportConfigurationOutput)
}

// FlagImportConfigurationArrayInput is an input type that accepts FlagImportConfigurationArray and FlagImportConfigurationArrayOutput values.
// You can construct a concrete instance of `FlagImportConfigurationArrayInput` via:
//
//	FlagImportConfigurationArray{ FlagImportConfigurationArgs{...} }
type FlagImportConfigurationArrayInput interface {
	pulumi.Input

	ToFlagImportConfigurationArrayOutput() FlagImportConfigurationArrayOutput
	ToFlagImportConfigurationArrayOutputWithContext(context.Context) FlagImportConfigurationArrayOutput
}

type FlagImportConfigurationArray []FlagImportConfigurationInput

func (FlagImportConfigurationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FlagImportConfiguration)(nil)).Elem()
}

func (i FlagImportConfigurationArray) ToFlagImportConfigurationArrayOutput() FlagImportConfigurationArrayOutput {
	return i.ToFlagImportConfigurationArrayOutputWithContext(context.Background())
}

func (i FlagImportConfigurationArray) ToFlagImportConfigurationArrayOutputWithContext(ctx context.Context) FlagImportConfigurationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FlagImportConfigurationArrayOutput)
}

// FlagImportConfigurationMapInput is an input type that accepts FlagImportConfigurationMap and FlagImportConfigurationMapOutput values.
// You can construct a concrete instance of `FlagImportConfigurationMapInput` via:
//
//	FlagImportConfigurationMap{ "key": FlagImportConfigurationArgs{...} }
type FlagImportConfigurationMapInput interface {
	pulumi.Input

	ToFlagImportConfigurationMapOutput() FlagImportConfigurationMapOutput
	ToFlagImportConfigurationMapOutputWithContext(context.Context) FlagImportConfigurationMapOutput
}

type FlagImportConfigurationMap map[string]FlagImportConfigurationInput

func (FlagImportConfigurationMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FlagImportConfiguration)(nil)).Elem()
}

func (i FlagImportConfigurationMap) ToFlagImportConfigurationMapOutput() FlagImportConfigurationMapOutput {
	return i.ToFlagImportConfigurationMapOutputWithContext(context.Background())
}

func (i FlagImportConfigurationMap) ToFlagImportConfigurationMapOutputWithContext(ctx context.Context) FlagImportConfigurationMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FlagImportConfigurationMapOutput)
}

type FlagImportConfigurationOutput struct{ *pulumi.OutputState }

func (FlagImportConfigurationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FlagImportConfiguration)(nil)).Elem()
}

func (o FlagImportConfigurationOutput) ToFlagImportConfigurationOutput() FlagImportConfigurationOutput {
	return o
}

func (o FlagImportConfigurationOutput) ToFlagImportConfigurationOutputWithContext(ctx context.Context) FlagImportConfigurationOutput {
	return o
}

// A JSON-encoded object of configuration values for the integration. The accepted keys vary by `integrationKey` and are described by the `formVariables` in the integration's manifest (often including a secret API token). Marked sensitive because it commonly contains credentials.
func (o FlagImportConfigurationOutput) Config() pulumi.StringOutput {
	return o.ApplyT(func(v *FlagImportConfiguration) pulumi.StringOutput { return v.Config }).(pulumi.StringOutput)
}

// The unique identifier the LaunchDarkly API assigns to this flag import configuration.
func (o FlagImportConfigurationOutput) IntegrationId() pulumi.StringOutput {
	return o.ApplyT(func(v *FlagImportConfiguration) pulumi.StringOutput { return v.IntegrationId }).(pulumi.StringOutput)
}

// The integration key identifying the external feature management system to import flags from, for example `split`. A change in this field forces the destruction of the existing resource and the creation of a new one.
func (o FlagImportConfigurationOutput) IntegrationKey() pulumi.StringOutput {
	return o.ApplyT(func(v *FlagImportConfiguration) pulumi.StringOutput { return v.IntegrationKey }).(pulumi.StringOutput)
}

// A human-friendly name for the flag import configuration. If not set, the LaunchDarkly API assigns a default.
func (o FlagImportConfigurationOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *FlagImportConfiguration) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The key of the project to import flags into. A change in this field forces the destruction of the existing resource and the creation of a new one.
func (o FlagImportConfigurationOutput) ProjectKey() pulumi.StringOutput {
	return o.ApplyT(func(v *FlagImportConfiguration) pulumi.StringOutput { return v.ProjectKey }).(pulumi.StringOutput)
}

// Tags associated with the flag import configuration.
func (o FlagImportConfigurationOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *FlagImportConfiguration) pulumi.StringArrayOutput { return v.Tags }).(pulumi.StringArrayOutput)
}

// The version of the flag import configuration.
func (o FlagImportConfigurationOutput) Version() pulumi.IntOutput {
	return o.ApplyT(func(v *FlagImportConfiguration) pulumi.IntOutput { return v.Version }).(pulumi.IntOutput)
}

type FlagImportConfigurationArrayOutput struct{ *pulumi.OutputState }

func (FlagImportConfigurationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FlagImportConfiguration)(nil)).Elem()
}

func (o FlagImportConfigurationArrayOutput) ToFlagImportConfigurationArrayOutput() FlagImportConfigurationArrayOutput {
	return o
}

func (o FlagImportConfigurationArrayOutput) ToFlagImportConfigurationArrayOutputWithContext(ctx context.Context) FlagImportConfigurationArrayOutput {
	return o
}

func (o FlagImportConfigurationArrayOutput) Index(i pulumi.IntInput) FlagImportConfigurationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FlagImportConfiguration {
		return vs[0].([]*FlagImportConfiguration)[vs[1].(int)]
	}).(FlagImportConfigurationOutput)
}

type FlagImportConfigurationMapOutput struct{ *pulumi.OutputState }

func (FlagImportConfigurationMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FlagImportConfiguration)(nil)).Elem()
}

func (o FlagImportConfigurationMapOutput) ToFlagImportConfigurationMapOutput() FlagImportConfigurationMapOutput {
	return o
}

func (o FlagImportConfigurationMapOutput) ToFlagImportConfigurationMapOutputWithContext(ctx context.Context) FlagImportConfigurationMapOutput {
	return o
}

func (o FlagImportConfigurationMapOutput) MapIndex(k pulumi.StringInput) FlagImportConfigurationOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FlagImportConfiguration {
		return vs[0].(map[string]*FlagImportConfiguration)[vs[1].(string)]
	}).(FlagImportConfigurationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FlagImportConfigurationInput)(nil)).Elem(), &FlagImportConfiguration{})
	pulumi.RegisterInputType(reflect.TypeOf((*FlagImportConfigurationArrayInput)(nil)).Elem(), FlagImportConfigurationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FlagImportConfigurationMapInput)(nil)).Elem(), FlagImportConfigurationMap{})
	pulumi.RegisterOutputType(FlagImportConfigurationOutput{})
	pulumi.RegisterOutputType(FlagImportConfigurationArrayOutput{})
	pulumi.RegisterOutputType(FlagImportConfigurationMapOutput{})
}
