// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package launchdarkly

import (
	"context"
	"reflect"

	"errors"
	"github.com/primait/pulumi-launchdarkly/sdk/go/launchdarkly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages the Custom flag-template settings for a LaunchDarkly project.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/primait/pulumi-launchdarkly/sdk/go/launchdarkly"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := launchdarkly.NewFlagTemplates(ctx, "example", &launchdarkly.FlagTemplatesArgs{
//				ProjectKey: pulumi.String("my-project"),
//				Tags: pulumi.StringArray{
//					pulumi.String("terraform"),
//				},
//				Temporary: pulumi.Bool(false),
//				BooleanDefaults: &launchdarkly.FlagTemplatesBooleanDefaultsArgs{
//					True_display_name:  "True",
//					False_display_name: "False",
//					True_description:   "",
//					False_description:  "",
//					On_variation:       0,
//					Off_variation:      1,
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// # LaunchDarkly flag templates can be imported using the project key
//
// ```sh
// $ pulumi import launchdarkly:index/flagTemplates:FlagTemplates example my-project
// ```
type FlagTemplates struct {
	pulumi.CustomResourceState

	// Default boolean variation settings.
	BooleanDefaults FlagTemplatesBooleanDefaultsOutput `pulumi:"booleanDefaults"`
	// The project key.
	ProjectKey pulumi.StringOutput      `pulumi:"projectKey"`
	Tags       pulumi.StringArrayOutput `pulumi:"tags"`
	Temporary  pulumi.BoolOutput        `pulumi:"temporary"`
}

// NewFlagTemplates registers a new resource with the given unique name, arguments, and options.
func NewFlagTemplates(ctx *pulumi.Context,
	name string, args *FlagTemplatesArgs, opts ...pulumi.ResourceOption) (*FlagTemplates, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.BooleanDefaults == nil {
		return nil, errors.New("invalid value for required argument 'BooleanDefaults'")
	}
	if args.ProjectKey == nil {
		return nil, errors.New("invalid value for required argument 'ProjectKey'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource FlagTemplates
	err := ctx.RegisterResource("launchdarkly:index/flagTemplates:FlagTemplates", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFlagTemplates gets an existing FlagTemplates resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFlagTemplates(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FlagTemplatesState, opts ...pulumi.ResourceOption) (*FlagTemplates, error) {
	var resource FlagTemplates
	err := ctx.ReadResource("launchdarkly:index/flagTemplates:FlagTemplates", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FlagTemplates resources.
type flagTemplatesState struct {
	// Default boolean variation settings.
	BooleanDefaults *FlagTemplatesBooleanDefaults `pulumi:"booleanDefaults"`
	// The project key.
	ProjectKey *string  `pulumi:"projectKey"`
	Tags       []string `pulumi:"tags"`
	Temporary  *bool    `pulumi:"temporary"`
}

type FlagTemplatesState struct {
	// Default boolean variation settings.
	BooleanDefaults FlagTemplatesBooleanDefaultsPtrInput
	// The project key.
	ProjectKey pulumi.StringPtrInput
	Tags       pulumi.StringArrayInput
	Temporary  pulumi.BoolPtrInput
}

func (FlagTemplatesState) ElementType() reflect.Type {
	return reflect.TypeOf((*flagTemplatesState)(nil)).Elem()
}

type flagTemplatesArgs struct {
	// Default boolean variation settings.
	BooleanDefaults FlagTemplatesBooleanDefaults `pulumi:"booleanDefaults"`
	// The project key.
	ProjectKey string   `pulumi:"projectKey"`
	Tags       []string `pulumi:"tags"`
	Temporary  *bool    `pulumi:"temporary"`
}

// The set of arguments for constructing a FlagTemplates resource.
type FlagTemplatesArgs struct {
	// Default boolean variation settings.
	BooleanDefaults FlagTemplatesBooleanDefaultsInput
	// The project key.
	ProjectKey pulumi.StringInput
	Tags       pulumi.StringArrayInput
	Temporary  pulumi.BoolPtrInput
}

func (FlagTemplatesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*flagTemplatesArgs)(nil)).Elem()
}

type FlagTemplatesInput interface {
	pulumi.Input

	ToFlagTemplatesOutput() FlagTemplatesOutput
	ToFlagTemplatesOutputWithContext(ctx context.Context) FlagTemplatesOutput
}

func (*FlagTemplates) ElementType() reflect.Type {
	return reflect.TypeOf((**FlagTemplates)(nil)).Elem()
}

func (i *FlagTemplates) ToFlagTemplatesOutput() FlagTemplatesOutput {
	return i.ToFlagTemplatesOutputWithContext(context.Background())
}

func (i *FlagTemplates) ToFlagTemplatesOutputWithContext(ctx context.Context) FlagTemplatesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FlagTemplatesOutput)
}

// FlagTemplatesArrayInput is an input type that accepts FlagTemplatesArray and FlagTemplatesArrayOutput values.
// You can construct a concrete instance of `FlagTemplatesArrayInput` via:
//
//	FlagTemplatesArray{ FlagTemplatesArgs{...} }
type FlagTemplatesArrayInput interface {
	pulumi.Input

	ToFlagTemplatesArrayOutput() FlagTemplatesArrayOutput
	ToFlagTemplatesArrayOutputWithContext(context.Context) FlagTemplatesArrayOutput
}

type FlagTemplatesArray []FlagTemplatesInput

func (FlagTemplatesArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FlagTemplates)(nil)).Elem()
}

func (i FlagTemplatesArray) ToFlagTemplatesArrayOutput() FlagTemplatesArrayOutput {
	return i.ToFlagTemplatesArrayOutputWithContext(context.Background())
}

func (i FlagTemplatesArray) ToFlagTemplatesArrayOutputWithContext(ctx context.Context) FlagTemplatesArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FlagTemplatesArrayOutput)
}

// FlagTemplatesMapInput is an input type that accepts FlagTemplatesMap and FlagTemplatesMapOutput values.
// You can construct a concrete instance of `FlagTemplatesMapInput` via:
//
//	FlagTemplatesMap{ "key": FlagTemplatesArgs{...} }
type FlagTemplatesMapInput interface {
	pulumi.Input

	ToFlagTemplatesMapOutput() FlagTemplatesMapOutput
	ToFlagTemplatesMapOutputWithContext(context.Context) FlagTemplatesMapOutput
}

type FlagTemplatesMap map[string]FlagTemplatesInput

func (FlagTemplatesMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FlagTemplates)(nil)).Elem()
}

func (i FlagTemplatesMap) ToFlagTemplatesMapOutput() FlagTemplatesMapOutput {
	return i.ToFlagTemplatesMapOutputWithContext(context.Background())
}

func (i FlagTemplatesMap) ToFlagTemplatesMapOutputWithContext(ctx context.Context) FlagTemplatesMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FlagTemplatesMapOutput)
}

type FlagTemplatesOutput struct{ *pulumi.OutputState }

func (FlagTemplatesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FlagTemplates)(nil)).Elem()
}

func (o FlagTemplatesOutput) ToFlagTemplatesOutput() FlagTemplatesOutput {
	return o
}

func (o FlagTemplatesOutput) ToFlagTemplatesOutputWithContext(ctx context.Context) FlagTemplatesOutput {
	return o
}

// Default boolean variation settings.
func (o FlagTemplatesOutput) BooleanDefaults() FlagTemplatesBooleanDefaultsOutput {
	return o.ApplyT(func(v *FlagTemplates) FlagTemplatesBooleanDefaultsOutput { return v.BooleanDefaults }).(FlagTemplatesBooleanDefaultsOutput)
}

// The project key.
func (o FlagTemplatesOutput) ProjectKey() pulumi.StringOutput {
	return o.ApplyT(func(v *FlagTemplates) pulumi.StringOutput { return v.ProjectKey }).(pulumi.StringOutput)
}

func (o FlagTemplatesOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *FlagTemplates) pulumi.StringArrayOutput { return v.Tags }).(pulumi.StringArrayOutput)
}

func (o FlagTemplatesOutput) Temporary() pulumi.BoolOutput {
	return o.ApplyT(func(v *FlagTemplates) pulumi.BoolOutput { return v.Temporary }).(pulumi.BoolOutput)
}

type FlagTemplatesArrayOutput struct{ *pulumi.OutputState }

func (FlagTemplatesArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FlagTemplates)(nil)).Elem()
}

func (o FlagTemplatesArrayOutput) ToFlagTemplatesArrayOutput() FlagTemplatesArrayOutput {
	return o
}

func (o FlagTemplatesArrayOutput) ToFlagTemplatesArrayOutputWithContext(ctx context.Context) FlagTemplatesArrayOutput {
	return o
}

func (o FlagTemplatesArrayOutput) Index(i pulumi.IntInput) FlagTemplatesOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FlagTemplates {
		return vs[0].([]*FlagTemplates)[vs[1].(int)]
	}).(FlagTemplatesOutput)
}

type FlagTemplatesMapOutput struct{ *pulumi.OutputState }

func (FlagTemplatesMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FlagTemplates)(nil)).Elem()
}

func (o FlagTemplatesMapOutput) ToFlagTemplatesMapOutput() FlagTemplatesMapOutput {
	return o
}

func (o FlagTemplatesMapOutput) ToFlagTemplatesMapOutputWithContext(ctx context.Context) FlagTemplatesMapOutput {
	return o
}

func (o FlagTemplatesMapOutput) MapIndex(k pulumi.StringInput) FlagTemplatesOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FlagTemplates {
		return vs[0].(map[string]*FlagTemplates)[vs[1].(string)]
	}).(FlagTemplatesOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FlagTemplatesInput)(nil)).Elem(), &FlagTemplates{})
	pulumi.RegisterInputType(reflect.TypeOf((*FlagTemplatesArrayInput)(nil)).Elem(), FlagTemplatesArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FlagTemplatesMapInput)(nil)).Elem(), FlagTemplatesMap{})
	pulumi.RegisterOutputType(FlagTemplatesOutput{})
	pulumi.RegisterOutputType(FlagTemplatesArrayOutput{})
	pulumi.RegisterOutputType(FlagTemplatesMapOutput{})
}
