// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package launchdarkly

import (
	"context"
	"reflect"

	"github.com/primait/pulumi-launchdarkly/sdk/go/launchdarkly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides a LaunchDarkly AI Config data source.
//
// This data source allows you to retrieve AI configuration information from your LaunchDarkly project.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/primait/pulumi-launchdarkly/sdk/go/launchdarkly"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := launchdarkly.GetAiConfig(ctx, &launchdarkly.LookupAiConfigArgs{
//				Key:        "customer-assistant",
//				ProjectKey: "example-project",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupAiConfig(ctx *pulumi.Context, args *LookupAiConfigArgs, opts ...pulumi.InvokeOption) (*LookupAiConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAiConfigResult
	err := ctx.Invoke("launchdarkly:index/getAiConfig:getAiConfig", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAiConfig.
type LookupAiConfigArgs struct {
	// The AI Config's unique key.
	Key string `pulumi:"key"`
	// The project key.
	ProjectKey string `pulumi:"projectKey"`
}

// A collection of values returned by getAiConfig.
type LookupAiConfigResult struct {
	// A timestamp of when the AI Config was created.
	CreationDate int `pulumi:"creationDate"`
	// The AI Config's description.
	Description string `pulumi:"description"`
	// The key of the evaluation metric associated with this AI Config.
	EvaluationMetricKey string `pulumi:"evaluationMetricKey"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Whether the evaluation metric is inverted.
	IsInverted bool `pulumi:"isInverted"`
	// The AI Config's unique key.
	Key string `pulumi:"key"`
	// The member ID of the maintainer for this AI Config. Conflicts with `maintainerTeamKey`.
	MaintainerId string `pulumi:"maintainerId"`
	// The team key of the maintainer team for this AI Config. Conflicts with `maintainerId`.
	MaintainerTeamKey string `pulumi:"maintainerTeamKey"`
	// The AI Config's mode. Must be `completion`, `agent`, or `judge`. Defaults to `completion`.
	Mode string `pulumi:"mode"`
	// The AI Config's human-readable name.
	Name string `pulumi:"name"`
	// The project key.
	ProjectKey string `pulumi:"projectKey"`
	// Tags associated with your resource.
	Tags []string `pulumi:"tags"`
	// A list of variation summaries for this AI Config.
	Variations []GetAiConfigVariationType `pulumi:"variations"`
	// The version of the AI Config.
	Version int `pulumi:"version"`
}

func LookupAiConfigOutput(ctx *pulumi.Context, args LookupAiConfigOutputArgs, opts ...pulumi.InvokeOption) LookupAiConfigResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupAiConfigResultOutput, error) {
			args := v.(LookupAiConfigArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("launchdarkly:index/getAiConfig:getAiConfig", args, LookupAiConfigResultOutput{}, options).(LookupAiConfigResultOutput), nil
		}).(LookupAiConfigResultOutput)
}

// A collection of arguments for invoking getAiConfig.
type LookupAiConfigOutputArgs struct {
	// The AI Config's unique key.
	Key pulumi.StringInput `pulumi:"key"`
	// The project key.
	ProjectKey pulumi.StringInput `pulumi:"projectKey"`
}

func (LookupAiConfigOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAiConfigArgs)(nil)).Elem()
}

// A collection of values returned by getAiConfig.
type LookupAiConfigResultOutput struct{ *pulumi.OutputState }

func (LookupAiConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAiConfigResult)(nil)).Elem()
}

func (o LookupAiConfigResultOutput) ToLookupAiConfigResultOutput() LookupAiConfigResultOutput {
	return o
}

func (o LookupAiConfigResultOutput) ToLookupAiConfigResultOutputWithContext(ctx context.Context) LookupAiConfigResultOutput {
	return o
}

// A timestamp of when the AI Config was created.
func (o LookupAiConfigResultOutput) CreationDate() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAiConfigResult) int { return v.CreationDate }).(pulumi.IntOutput)
}

// The AI Config's description.
func (o LookupAiConfigResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAiConfigResult) string { return v.Description }).(pulumi.StringOutput)
}

// The key of the evaluation metric associated with this AI Config.
func (o LookupAiConfigResultOutput) EvaluationMetricKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAiConfigResult) string { return v.EvaluationMetricKey }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupAiConfigResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAiConfigResult) string { return v.Id }).(pulumi.StringOutput)
}

// Whether the evaluation metric is inverted.
func (o LookupAiConfigResultOutput) IsInverted() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAiConfigResult) bool { return v.IsInverted }).(pulumi.BoolOutput)
}

// The AI Config's unique key.
func (o LookupAiConfigResultOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAiConfigResult) string { return v.Key }).(pulumi.StringOutput)
}

// The member ID of the maintainer for this AI Config. Conflicts with `maintainerTeamKey`.
func (o LookupAiConfigResultOutput) MaintainerId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAiConfigResult) string { return v.MaintainerId }).(pulumi.StringOutput)
}

// The team key of the maintainer team for this AI Config. Conflicts with `maintainerId`.
func (o LookupAiConfigResultOutput) MaintainerTeamKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAiConfigResult) string { return v.MaintainerTeamKey }).(pulumi.StringOutput)
}

// The AI Config's mode. Must be `completion`, `agent`, or `judge`. Defaults to `completion`.
func (o LookupAiConfigResultOutput) Mode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAiConfigResult) string { return v.Mode }).(pulumi.StringOutput)
}

// The AI Config's human-readable name.
func (o LookupAiConfigResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAiConfigResult) string { return v.Name }).(pulumi.StringOutput)
}

// The project key.
func (o LookupAiConfigResultOutput) ProjectKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAiConfigResult) string { return v.ProjectKey }).(pulumi.StringOutput)
}

// Tags associated with your resource.
func (o LookupAiConfigResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupAiConfigResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

// A list of variation summaries for this AI Config.
func (o LookupAiConfigResultOutput) Variations() GetAiConfigVariationTypeArrayOutput {
	return o.ApplyT(func(v LookupAiConfigResult) []GetAiConfigVariationType { return v.Variations }).(GetAiConfigVariationTypeArrayOutput)
}

// The version of the AI Config.
func (o LookupAiConfigResultOutput) Version() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAiConfigResult) int { return v.Version }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAiConfigResultOutput{})
}
