// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package launchdarkly

import (
	"context"
	"reflect"

	"github.com/primait/pulumi-launchdarkly/sdk/go/launchdarkly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Reads a LaunchDarkly context kind by project + key. Useful for inspecting the built-in `user` kind or any kind managed outside Terraform.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/primait/pulumi-launchdarkly/sdk/go/launchdarkly"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := launchdarkly.GetContextKind(ctx, &launchdarkly.LookupContextKindArgs{
//				ProjectKey: "default",
//				Key:        "user",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupContextKind(ctx *pulumi.Context, args *LookupContextKindArgs, opts ...pulumi.InvokeOption) (*LookupContextKindResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupContextKindResult
	err := ctx.Invoke("launchdarkly:index/getContextKind:getContextKind", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getContextKind.
type LookupContextKindArgs struct {
	// The unique identifier of the context kind within the project.
	Key string `pulumi:"key"`
	// The LaunchDarkly project key that scopes the context kind.
	ProjectKey string `pulumi:"projectKey"`
}

// A collection of values returned by getContextKind.
type LookupContextKindResult struct {
	// Whether the context kind is archived. Archived kinds are unavailable for targeting.
	Archived bool `pulumi:"archived"`
	// How the context kind was first created.
	CreatedFrom string `pulumi:"createdFrom"`
	// Unix epoch (milliseconds) at which the context kind was created.
	CreationDate int `pulumi:"creationDate"`
	// The description of the context kind.
	Description string `pulumi:"description"`
	// Whether the context kind is hidden from targeting UIs.
	HideInTargeting bool `pulumi:"hideInTargeting"`
	// The composite identifier `<project_key>/<key>`.
	Id string `pulumi:"id"`
	// The unique identifier of the context kind within the project.
	Key string `pulumi:"key"`
	// Unix epoch (milliseconds) of the last server-side modification.
	LastModified int `pulumi:"lastModified"`
	// The human-readable name of the context kind.
	Name string `pulumi:"name"`
	// The LaunchDarkly project key that scopes the context kind.
	ProjectKey string `pulumi:"projectKey"`
	// The LaunchDarkly-assigned version.
	Version int `pulumi:"version"`
}

func LookupContextKindOutput(ctx *pulumi.Context, args LookupContextKindOutputArgs, opts ...pulumi.InvokeOption) LookupContextKindResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupContextKindResultOutput, error) {
			args := v.(LookupContextKindArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("launchdarkly:index/getContextKind:getContextKind", args, LookupContextKindResultOutput{}, options).(LookupContextKindResultOutput), nil
		}).(LookupContextKindResultOutput)
}

// A collection of arguments for invoking getContextKind.
type LookupContextKindOutputArgs struct {
	// The unique identifier of the context kind within the project.
	Key pulumi.StringInput `pulumi:"key"`
	// The LaunchDarkly project key that scopes the context kind.
	ProjectKey pulumi.StringInput `pulumi:"projectKey"`
}

func (LookupContextKindOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupContextKindArgs)(nil)).Elem()
}

// A collection of values returned by getContextKind.
type LookupContextKindResultOutput struct{ *pulumi.OutputState }

func (LookupContextKindResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupContextKindResult)(nil)).Elem()
}

func (o LookupContextKindResultOutput) ToLookupContextKindResultOutput() LookupContextKindResultOutput {
	return o
}

func (o LookupContextKindResultOutput) ToLookupContextKindResultOutputWithContext(ctx context.Context) LookupContextKindResultOutput {
	return o
}

// Whether the context kind is archived. Archived kinds are unavailable for targeting.
func (o LookupContextKindResultOutput) Archived() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupContextKindResult) bool { return v.Archived }).(pulumi.BoolOutput)
}

// How the context kind was first created.
func (o LookupContextKindResultOutput) CreatedFrom() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContextKindResult) string { return v.CreatedFrom }).(pulumi.StringOutput)
}

// Unix epoch (milliseconds) at which the context kind was created.
func (o LookupContextKindResultOutput) CreationDate() pulumi.IntOutput {
	return o.ApplyT(func(v LookupContextKindResult) int { return v.CreationDate }).(pulumi.IntOutput)
}

// The description of the context kind.
func (o LookupContextKindResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContextKindResult) string { return v.Description }).(pulumi.StringOutput)
}

// Whether the context kind is hidden from targeting UIs.
func (o LookupContextKindResultOutput) HideInTargeting() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupContextKindResult) bool { return v.HideInTargeting }).(pulumi.BoolOutput)
}

// The composite identifier `<project_key>/<key>`.
func (o LookupContextKindResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContextKindResult) string { return v.Id }).(pulumi.StringOutput)
}

// The unique identifier of the context kind within the project.
func (o LookupContextKindResultOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContextKindResult) string { return v.Key }).(pulumi.StringOutput)
}

// Unix epoch (milliseconds) of the last server-side modification.
func (o LookupContextKindResultOutput) LastModified() pulumi.IntOutput {
	return o.ApplyT(func(v LookupContextKindResult) int { return v.LastModified }).(pulumi.IntOutput)
}

// The human-readable name of the context kind.
func (o LookupContextKindResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContextKindResult) string { return v.Name }).(pulumi.StringOutput)
}

// The LaunchDarkly project key that scopes the context kind.
func (o LookupContextKindResultOutput) ProjectKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContextKindResult) string { return v.ProjectKey }).(pulumi.StringOutput)
}

// The LaunchDarkly-assigned version.
func (o LookupContextKindResultOutput) Version() pulumi.IntOutput {
	return o.ApplyT(func(v LookupContextKindResult) int { return v.Version }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupContextKindResultOutput{})
}
