// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package launchdarkly

import (
	"context"
	"reflect"

	"github.com/primait/pulumi-launchdarkly/sdk/go/launchdarkly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides a LaunchDarkly model config data source.
//
// This data source allows you to retrieve AI model configuration information from your LaunchDarkly project.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/primait/pulumi-launchdarkly/sdk/go/launchdarkly"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := launchdarkly.GetModelConfig(ctx, &launchdarkly.LookupModelConfigArgs{
//				Key:        "gpt-4-turbo",
//				ProjectKey: "example-project",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupModelConfig(ctx *pulumi.Context, args *LookupModelConfigArgs, opts ...pulumi.InvokeOption) (*LookupModelConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupModelConfigResult
	err := ctx.Invoke("launchdarkly:index/getModelConfig:getModelConfig", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getModelConfig.
type LookupModelConfigArgs struct {
	// The model config's unique key.
	Key string `pulumi:"key"`
	// The project key.
	ProjectKey string `pulumi:"projectKey"`
}

// A collection of values returned by getModelConfig.
type LookupModelConfigResult struct {
	// The cost per input token for the model.
	CostPerInputToken float64 `pulumi:"costPerInputToken"`
	// The cost per output token for the model.
	CostPerOutputToken float64 `pulumi:"costPerOutputToken"`
	// A JSON string representing custom parameters for the model config.
	CustomParameters string `pulumi:"customParameters"`
	// Whether the model config is available globally.
	Global bool `pulumi:"global"`
	// The icon for the model config.
	Icon string `pulumi:"icon"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The model config's unique key.
	Key string `pulumi:"key"`
	// The model identifier (e.g. `gpt-4`, `claude-3`).
	ModelId string `pulumi:"modelId"`
	// The provider name for the model config (e.g. `openai`, `anthropic`).
	ModelProvider string `pulumi:"modelProvider"`
	// The model config's human-readable name.
	Name string `pulumi:"name"`
	// A JSON string representing the model parameters (e.g. `{"temperature": 0.7, "maxTokens": 4096}`).
	Params string `pulumi:"params"`
	// The project key.
	ProjectKey string `pulumi:"projectKey"`
	// Tags associated with your resource.
	Tags []string `pulumi:"tags"`
	// The version of the model config.
	Version int `pulumi:"version"`
}

func LookupModelConfigOutput(ctx *pulumi.Context, args LookupModelConfigOutputArgs, opts ...pulumi.InvokeOption) LookupModelConfigResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupModelConfigResultOutput, error) {
			args := v.(LookupModelConfigArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("launchdarkly:index/getModelConfig:getModelConfig", args, LookupModelConfigResultOutput{}, options).(LookupModelConfigResultOutput), nil
		}).(LookupModelConfigResultOutput)
}

// A collection of arguments for invoking getModelConfig.
type LookupModelConfigOutputArgs struct {
	// The model config's unique key.
	Key pulumi.StringInput `pulumi:"key"`
	// The project key.
	ProjectKey pulumi.StringInput `pulumi:"projectKey"`
}

func (LookupModelConfigOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupModelConfigArgs)(nil)).Elem()
}

// A collection of values returned by getModelConfig.
type LookupModelConfigResultOutput struct{ *pulumi.OutputState }

func (LookupModelConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupModelConfigResult)(nil)).Elem()
}

func (o LookupModelConfigResultOutput) ToLookupModelConfigResultOutput() LookupModelConfigResultOutput {
	return o
}

func (o LookupModelConfigResultOutput) ToLookupModelConfigResultOutputWithContext(ctx context.Context) LookupModelConfigResultOutput {
	return o
}

// The cost per input token for the model.
func (o LookupModelConfigResultOutput) CostPerInputToken() pulumi.Float64Output {
	return o.ApplyT(func(v LookupModelConfigResult) float64 { return v.CostPerInputToken }).(pulumi.Float64Output)
}

// The cost per output token for the model.
func (o LookupModelConfigResultOutput) CostPerOutputToken() pulumi.Float64Output {
	return o.ApplyT(func(v LookupModelConfigResult) float64 { return v.CostPerOutputToken }).(pulumi.Float64Output)
}

// A JSON string representing custom parameters for the model config.
func (o LookupModelConfigResultOutput) CustomParameters() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelConfigResult) string { return v.CustomParameters }).(pulumi.StringOutput)
}

// Whether the model config is available globally.
func (o LookupModelConfigResultOutput) Global() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupModelConfigResult) bool { return v.Global }).(pulumi.BoolOutput)
}

// The icon for the model config.
func (o LookupModelConfigResultOutput) Icon() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelConfigResult) string { return v.Icon }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupModelConfigResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelConfigResult) string { return v.Id }).(pulumi.StringOutput)
}

// The model config's unique key.
func (o LookupModelConfigResultOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelConfigResult) string { return v.Key }).(pulumi.StringOutput)
}

// The model identifier (e.g. `gpt-4`, `claude-3`).
func (o LookupModelConfigResultOutput) ModelId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelConfigResult) string { return v.ModelId }).(pulumi.StringOutput)
}

// The provider name for the model config (e.g. `openai`, `anthropic`).
func (o LookupModelConfigResultOutput) ModelProvider() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelConfigResult) string { return v.ModelProvider }).(pulumi.StringOutput)
}

// The model config's human-readable name.
func (o LookupModelConfigResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelConfigResult) string { return v.Name }).(pulumi.StringOutput)
}

// A JSON string representing the model parameters (e.g. `{"temperature": 0.7, "maxTokens": 4096}`).
func (o LookupModelConfigResultOutput) Params() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelConfigResult) string { return v.Params }).(pulumi.StringOutput)
}

// The project key.
func (o LookupModelConfigResultOutput) ProjectKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupModelConfigResult) string { return v.ProjectKey }).(pulumi.StringOutput)
}

// Tags associated with your resource.
func (o LookupModelConfigResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupModelConfigResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

// The version of the model config.
func (o LookupModelConfigResultOutput) Version() pulumi.IntOutput {
	return o.ApplyT(func(v LookupModelConfigResult) int { return v.Version }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupModelConfigResultOutput{})
}
