// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package launchdarkly

import (
	"context"
	"reflect"

	"github.com/primait/pulumi-launchdarkly/sdk/go/launchdarkly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the launchdarkly package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// The [personal access token](https://docs.launchdarkly.com/home/account-security/api-access-tokens#personal-tokens) or
	// [service token](https://docs.launchdarkly.com/home/account-security/api-access-tokens#service-tokens) used to
	// authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_ACCESS_TOKEN` environment variable. You
	// must provide either `accessToken` or `oauthToken`.
	Access_token pulumi.StringPtrOutput `pulumi:"access_token"`
	// The LaunchDarkly host address. If this argument is not specified, the default host address is
	// `https://app.launchdarkly.com`
	Api_host pulumi.StringPtrOutput `pulumi:"api_host"`
	// An OAuth V2 token you use to authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_OAUTH_TOKEN`
	// environment variable. You must provide either `accessToken` or `oauthToken`.
	Oauth_token pulumi.StringPtrOutput `pulumi:"oauth_token"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.Access_token != nil {
		args.Access_token = pulumi.ToSecret(args.Access_token).(pulumi.StringPtrInput)
	}
	if args.Oauth_token != nil {
		args.Oauth_token = pulumi.ToSecret(args.Oauth_token).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"access_token",
		"oauth_token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:launchdarkly", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// The [personal access token](https://docs.launchdarkly.com/home/account-security/api-access-tokens#personal-tokens) or
	// [service token](https://docs.launchdarkly.com/home/account-security/api-access-tokens#service-tokens) used to
	// authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_ACCESS_TOKEN` environment variable. You
	// must provide either `accessToken` or `oauthToken`.
	Access_token *string `pulumi:"access_token"`
	// The LaunchDarkly host address. If this argument is not specified, the default host address is
	// `https://app.launchdarkly.com`
	Api_host *string `pulumi:"api_host"`
	// The HTTP timeout (in seconds) when making API calls to LaunchDarkly.
	Http_timeout *int `pulumi:"http_timeout"`
	// An OAuth V2 token you use to authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_OAUTH_TOKEN`
	// environment variable. You must provide either `accessToken` or `oauthToken`.
	Oauth_token *string `pulumi:"oauth_token"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// The [personal access token](https://docs.launchdarkly.com/home/account-security/api-access-tokens#personal-tokens) or
	// [service token](https://docs.launchdarkly.com/home/account-security/api-access-tokens#service-tokens) used to
	// authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_ACCESS_TOKEN` environment variable. You
	// must provide either `accessToken` or `oauthToken`.
	Access_token pulumi.StringPtrInput
	// The LaunchDarkly host address. If this argument is not specified, the default host address is
	// `https://app.launchdarkly.com`
	Api_host pulumi.StringPtrInput
	// The HTTP timeout (in seconds) when making API calls to LaunchDarkly.
	Http_timeout pulumi.IntPtrInput
	// An OAuth V2 token you use to authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_OAUTH_TOKEN`
	// environment variable. You must provide either `accessToken` or `oauthToken`.
	Oauth_token pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// The [personal access token](https://docs.launchdarkly.com/home/account-security/api-access-tokens#personal-tokens) or
// [service token](https://docs.launchdarkly.com/home/account-security/api-access-tokens#service-tokens) used to
// authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_ACCESS_TOKEN` environment variable. You
// must provide either `accessToken` or `oauthToken`.
func (o ProviderOutput) Access_token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Access_token }).(pulumi.StringPtrOutput)
}

// The LaunchDarkly host address. If this argument is not specified, the default host address is
// `https://app.launchdarkly.com`
func (o ProviderOutput) Api_host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Api_host }).(pulumi.StringPtrOutput)
}

// An OAuth V2 token you use to authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_OAUTH_TOKEN`
// environment variable. You must provide either `accessToken` or `oauthToken`.
func (o ProviderOutput) Oauth_token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Oauth_token }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
