// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package launchdarkly

import (
	"context"
	"reflect"

	"errors"
	"github.com/primait/pulumi-launchdarkly/sdk/go/launchdarkly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides a LaunchDarkly release policy resource.
//
// > **Beta:** This resource wraps a beta LaunchDarkly API (the `release-policies` endpoints, accessed with the `LD-API-Version: beta` header). Beta resources may change or be removed in future versions.
//
// This resource lets you create and manage [release policies](https://launchdarkly.com/docs/home/releases/release-policies) within a LaunchDarkly project. A release policy defines how flag changes roll out to environments, either as a `guarded-release`, which monitors the rollout against metrics with optional automatic rollback, or a `progressive-release`, which advances the rollout through a fixed schedule of allocation stages.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/primait/pulumi-launchdarkly/sdk/go/launchdarkly"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := launchdarkly.NewReleasePolicy(ctx, "guarded_checkout", &launchdarkly.ReleasePolicyArgs{
//				ProjectKey:    pulumi.Any(example.Key),
//				Key:           pulumi.String("guarded-checkout"),
//				Name:          pulumi.String("Guarded checkout rollout"),
//				ReleaseMethod: pulumi.String("guarded-release"),
//				Scope: &launchdarkly.ReleasePolicyScopeArgs{
//					Environment_keys: []string{
//						"production",
//					},
//					Flag_tag_keys: []string{
//						"checkout",
//					},
//				},
//				GuardedReleaseConfig: &launchdarkly.ReleasePolicyGuardedReleaseConfigArgs{
//					Rollout_context_kind:   "user",
//					Min_sample_size:        1000,
//					Rollback_on_regression: true,
//					Metric_keys: []interface{}{
//						completedPurchase.Key,
//					},
//					Stages: launchdarkly.ReleasePolicyGuardedReleaseConfigStageArray{
//						&launchdarkly.ReleasePolicyGuardedReleaseConfigStageArgs{
//							Allocation:     pulumi.Int(10),
//							DurationMillis: pulumi.Int(3600000),
//						},
//						&launchdarkly.ReleasePolicyGuardedReleaseConfigStageArgs{
//							Allocation:     pulumi.Int(50),
//							DurationMillis: pulumi.Int(3600000),
//						},
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = launchdarkly.NewReleasePolicy(ctx, "progressive_rollout", &launchdarkly.ReleasePolicyArgs{
//				ProjectKey:    pulumi.Any(example.Key),
//				Key:           pulumi.String("progressive-rollout"),
//				Name:          pulumi.String("Progressive rollout"),
//				ReleaseMethod: pulumi.String("progressive-release"),
//				Scope: &launchdarkly.ReleasePolicyScopeArgs{
//					Environment_keys: []string{
//						"production",
//					},
//				},
//				ProgressiveReleaseConfig: &launchdarkly.ReleasePolicyProgressiveReleaseConfigArgs{
//					Rollout_context_kind: "user",
//					Stages: launchdarkly.ReleasePolicyProgressiveReleaseConfigStageArray{
//						&launchdarkly.ReleasePolicyProgressiveReleaseConfigStageArgs{
//							Allocation:     pulumi.Int(20),
//							DurationMillis: pulumi.Int(3600000),
//						},
//						&launchdarkly.ReleasePolicyProgressiveReleaseConfigStageArgs{
//							Allocation:     pulumi.Int(60),
//							DurationMillis: pulumi.Int(3600000),
//						},
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// A release policy can be imported using the project key and release policy key
// joined by a slash: project_key/release_policy_key.
//
// ```sh
// $ pulumi import launchdarkly:index/releasePolicy:ReleasePolicy guarded_checkout example-project/guarded-checkout
// ```
type ReleasePolicy struct {
	pulumi.CustomResourceState

	// Configuration for a `guarded-release`. May only be set when `releaseMethod` is `guarded-release`.
	GuardedReleaseConfig ReleasePolicyGuardedReleaseConfigPtrOutput `pulumi:"guardedReleaseConfig"`
	// The unique human-readable key that references the release policy. A change in this field forces the destruction of the existing resource and the creation of a new one.
	Key pulumi.StringOutput `pulumi:"key"`
	// The human-friendly name for the release policy.
	Name pulumi.StringOutput `pulumi:"name"`
	// Configuration for a `progressive-release`. May only be set when `releaseMethod` is `progressive-release`.
	ProgressiveReleaseConfig ReleasePolicyProgressiveReleaseConfigPtrOutput `pulumi:"progressiveReleaseConfig"`
	// The release policy's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
	ProjectKey pulumi.StringOutput `pulumi:"projectKey"`
	// The rank of the release policy within the project. LaunchDarkly assigns and orders the rank. Reorder release policies in the LaunchDarkly UI.
	Rank pulumi.IntOutput `pulumi:"rank"`
	// The release method this policy uses. Must be one of `guarded-release` or `progressive-release`. Set `guardedReleaseConfig` for a `guarded-release` and `progressiveReleaseConfig` for a `progressive-release`.
	ReleaseMethod pulumi.StringOutput `pulumi:"releaseMethod"`
	// The scope that determines which environments and flags this release policy applies to.
	Scope ReleasePolicyScopePtrOutput `pulumi:"scope"`
}

// NewReleasePolicy registers a new resource with the given unique name, arguments, and options.
func NewReleasePolicy(ctx *pulumi.Context,
	name string, args *ReleasePolicyArgs, opts ...pulumi.ResourceOption) (*ReleasePolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Key == nil {
		return nil, errors.New("invalid value for required argument 'Key'")
	}
	if args.ProjectKey == nil {
		return nil, errors.New("invalid value for required argument 'ProjectKey'")
	}
	if args.ReleaseMethod == nil {
		return nil, errors.New("invalid value for required argument 'ReleaseMethod'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ReleasePolicy
	err := ctx.RegisterResource("launchdarkly:index/releasePolicy:ReleasePolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetReleasePolicy gets an existing ReleasePolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetReleasePolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ReleasePolicyState, opts ...pulumi.ResourceOption) (*ReleasePolicy, error) {
	var resource ReleasePolicy
	err := ctx.ReadResource("launchdarkly:index/releasePolicy:ReleasePolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ReleasePolicy resources.
type releasePolicyState struct {
	// Configuration for a `guarded-release`. May only be set when `releaseMethod` is `guarded-release`.
	GuardedReleaseConfig *ReleasePolicyGuardedReleaseConfig `pulumi:"guardedReleaseConfig"`
	// The unique human-readable key that references the release policy. A change in this field forces the destruction of the existing resource and the creation of a new one.
	Key *string `pulumi:"key"`
	// The human-friendly name for the release policy.
	Name *string `pulumi:"name"`
	// Configuration for a `progressive-release`. May only be set when `releaseMethod` is `progressive-release`.
	ProgressiveReleaseConfig *ReleasePolicyProgressiveReleaseConfig `pulumi:"progressiveReleaseConfig"`
	// The release policy's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
	ProjectKey *string `pulumi:"projectKey"`
	// The rank of the release policy within the project. LaunchDarkly assigns and orders the rank. Reorder release policies in the LaunchDarkly UI.
	Rank *int `pulumi:"rank"`
	// The release method this policy uses. Must be one of `guarded-release` or `progressive-release`. Set `guardedReleaseConfig` for a `guarded-release` and `progressiveReleaseConfig` for a `progressive-release`.
	ReleaseMethod *string `pulumi:"releaseMethod"`
	// The scope that determines which environments and flags this release policy applies to.
	Scope *ReleasePolicyScope `pulumi:"scope"`
}

type ReleasePolicyState struct {
	// Configuration for a `guarded-release`. May only be set when `releaseMethod` is `guarded-release`.
	GuardedReleaseConfig ReleasePolicyGuardedReleaseConfigPtrInput
	// The unique human-readable key that references the release policy. A change in this field forces the destruction of the existing resource and the creation of a new one.
	Key pulumi.StringPtrInput
	// The human-friendly name for the release policy.
	Name pulumi.StringPtrInput
	// Configuration for a `progressive-release`. May only be set when `releaseMethod` is `progressive-release`.
	ProgressiveReleaseConfig ReleasePolicyProgressiveReleaseConfigPtrInput
	// The release policy's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
	ProjectKey pulumi.StringPtrInput
	// The rank of the release policy within the project. LaunchDarkly assigns and orders the rank. Reorder release policies in the LaunchDarkly UI.
	Rank pulumi.IntPtrInput
	// The release method this policy uses. Must be one of `guarded-release` or `progressive-release`. Set `guardedReleaseConfig` for a `guarded-release` and `progressiveReleaseConfig` for a `progressive-release`.
	ReleaseMethod pulumi.StringPtrInput
	// The scope that determines which environments and flags this release policy applies to.
	Scope ReleasePolicyScopePtrInput
}

func (ReleasePolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*releasePolicyState)(nil)).Elem()
}

type releasePolicyArgs struct {
	// Configuration for a `guarded-release`. May only be set when `releaseMethod` is `guarded-release`.
	GuardedReleaseConfig *ReleasePolicyGuardedReleaseConfig `pulumi:"guardedReleaseConfig"`
	// The unique human-readable key that references the release policy. A change in this field forces the destruction of the existing resource and the creation of a new one.
	Key string `pulumi:"key"`
	// The human-friendly name for the release policy.
	Name *string `pulumi:"name"`
	// Configuration for a `progressive-release`. May only be set when `releaseMethod` is `progressive-release`.
	ProgressiveReleaseConfig *ReleasePolicyProgressiveReleaseConfig `pulumi:"progressiveReleaseConfig"`
	// The release policy's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
	ProjectKey string `pulumi:"projectKey"`
	// The release method this policy uses. Must be one of `guarded-release` or `progressive-release`. Set `guardedReleaseConfig` for a `guarded-release` and `progressiveReleaseConfig` for a `progressive-release`.
	ReleaseMethod string `pulumi:"releaseMethod"`
	// The scope that determines which environments and flags this release policy applies to.
	Scope *ReleasePolicyScope `pulumi:"scope"`
}

// The set of arguments for constructing a ReleasePolicy resource.
type ReleasePolicyArgs struct {
	// Configuration for a `guarded-release`. May only be set when `releaseMethod` is `guarded-release`.
	GuardedReleaseConfig ReleasePolicyGuardedReleaseConfigPtrInput
	// The unique human-readable key that references the release policy. A change in this field forces the destruction of the existing resource and the creation of a new one.
	Key pulumi.StringInput
	// The human-friendly name for the release policy.
	Name pulumi.StringPtrInput
	// Configuration for a `progressive-release`. May only be set when `releaseMethod` is `progressive-release`.
	ProgressiveReleaseConfig ReleasePolicyProgressiveReleaseConfigPtrInput
	// The release policy's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
	ProjectKey pulumi.StringInput
	// The release method this policy uses. Must be one of `guarded-release` or `progressive-release`. Set `guardedReleaseConfig` for a `guarded-release` and `progressiveReleaseConfig` for a `progressive-release`.
	ReleaseMethod pulumi.StringInput
	// The scope that determines which environments and flags this release policy applies to.
	Scope ReleasePolicyScopePtrInput
}

func (ReleasePolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*releasePolicyArgs)(nil)).Elem()
}

type ReleasePolicyInput interface {
	pulumi.Input

	ToReleasePolicyOutput() ReleasePolicyOutput
	ToReleasePolicyOutputWithContext(ctx context.Context) ReleasePolicyOutput
}

func (*ReleasePolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**ReleasePolicy)(nil)).Elem()
}

func (i *ReleasePolicy) ToReleasePolicyOutput() ReleasePolicyOutput {
	return i.ToReleasePolicyOutputWithContext(context.Background())
}

func (i *ReleasePolicy) ToReleasePolicyOutputWithContext(ctx context.Context) ReleasePolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReleasePolicyOutput)
}

// ReleasePolicyArrayInput is an input type that accepts ReleasePolicyArray and ReleasePolicyArrayOutput values.
// You can construct a concrete instance of `ReleasePolicyArrayInput` via:
//
//	ReleasePolicyArray{ ReleasePolicyArgs{...} }
type ReleasePolicyArrayInput interface {
	pulumi.Input

	ToReleasePolicyArrayOutput() ReleasePolicyArrayOutput
	ToReleasePolicyArrayOutputWithContext(context.Context) ReleasePolicyArrayOutput
}

type ReleasePolicyArray []ReleasePolicyInput

func (ReleasePolicyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ReleasePolicy)(nil)).Elem()
}

func (i ReleasePolicyArray) ToReleasePolicyArrayOutput() ReleasePolicyArrayOutput {
	return i.ToReleasePolicyArrayOutputWithContext(context.Background())
}

func (i ReleasePolicyArray) ToReleasePolicyArrayOutputWithContext(ctx context.Context) ReleasePolicyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReleasePolicyArrayOutput)
}

// ReleasePolicyMapInput is an input type that accepts ReleasePolicyMap and ReleasePolicyMapOutput values.
// You can construct a concrete instance of `ReleasePolicyMapInput` via:
//
//	ReleasePolicyMap{ "key": ReleasePolicyArgs{...} }
type ReleasePolicyMapInput interface {
	pulumi.Input

	ToReleasePolicyMapOutput() ReleasePolicyMapOutput
	ToReleasePolicyMapOutputWithContext(context.Context) ReleasePolicyMapOutput
}

type ReleasePolicyMap map[string]ReleasePolicyInput

func (ReleasePolicyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ReleasePolicy)(nil)).Elem()
}

func (i ReleasePolicyMap) ToReleasePolicyMapOutput() ReleasePolicyMapOutput {
	return i.ToReleasePolicyMapOutputWithContext(context.Background())
}

func (i ReleasePolicyMap) ToReleasePolicyMapOutputWithContext(ctx context.Context) ReleasePolicyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReleasePolicyMapOutput)
}

type ReleasePolicyOutput struct{ *pulumi.OutputState }

func (ReleasePolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ReleasePolicy)(nil)).Elem()
}

func (o ReleasePolicyOutput) ToReleasePolicyOutput() ReleasePolicyOutput {
	return o
}

func (o ReleasePolicyOutput) ToReleasePolicyOutputWithContext(ctx context.Context) ReleasePolicyOutput {
	return o
}

// Configuration for a `guarded-release`. May only be set when `releaseMethod` is `guarded-release`.
func (o ReleasePolicyOutput) GuardedReleaseConfig() ReleasePolicyGuardedReleaseConfigPtrOutput {
	return o.ApplyT(func(v *ReleasePolicy) ReleasePolicyGuardedReleaseConfigPtrOutput { return v.GuardedReleaseConfig }).(ReleasePolicyGuardedReleaseConfigPtrOutput)
}

// The unique human-readable key that references the release policy. A change in this field forces the destruction of the existing resource and the creation of a new one.
func (o ReleasePolicyOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v *ReleasePolicy) pulumi.StringOutput { return v.Key }).(pulumi.StringOutput)
}

// The human-friendly name for the release policy.
func (o ReleasePolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ReleasePolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Configuration for a `progressive-release`. May only be set when `releaseMethod` is `progressive-release`.
func (o ReleasePolicyOutput) ProgressiveReleaseConfig() ReleasePolicyProgressiveReleaseConfigPtrOutput {
	return o.ApplyT(func(v *ReleasePolicy) ReleasePolicyProgressiveReleaseConfigPtrOutput {
		return v.ProgressiveReleaseConfig
	}).(ReleasePolicyProgressiveReleaseConfigPtrOutput)
}

// The release policy's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
func (o ReleasePolicyOutput) ProjectKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ReleasePolicy) pulumi.StringOutput { return v.ProjectKey }).(pulumi.StringOutput)
}

// The rank of the release policy within the project. LaunchDarkly assigns and orders the rank. Reorder release policies in the LaunchDarkly UI.
func (o ReleasePolicyOutput) Rank() pulumi.IntOutput {
	return o.ApplyT(func(v *ReleasePolicy) pulumi.IntOutput { return v.Rank }).(pulumi.IntOutput)
}

// The release method this policy uses. Must be one of `guarded-release` or `progressive-release`. Set `guardedReleaseConfig` for a `guarded-release` and `progressiveReleaseConfig` for a `progressive-release`.
func (o ReleasePolicyOutput) ReleaseMethod() pulumi.StringOutput {
	return o.ApplyT(func(v *ReleasePolicy) pulumi.StringOutput { return v.ReleaseMethod }).(pulumi.StringOutput)
}

// The scope that determines which environments and flags this release policy applies to.
func (o ReleasePolicyOutput) Scope() ReleasePolicyScopePtrOutput {
	return o.ApplyT(func(v *ReleasePolicy) ReleasePolicyScopePtrOutput { return v.Scope }).(ReleasePolicyScopePtrOutput)
}

type ReleasePolicyArrayOutput struct{ *pulumi.OutputState }

func (ReleasePolicyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ReleasePolicy)(nil)).Elem()
}

func (o ReleasePolicyArrayOutput) ToReleasePolicyArrayOutput() ReleasePolicyArrayOutput {
	return o
}

func (o ReleasePolicyArrayOutput) ToReleasePolicyArrayOutputWithContext(ctx context.Context) ReleasePolicyArrayOutput {
	return o
}

func (o ReleasePolicyArrayOutput) Index(i pulumi.IntInput) ReleasePolicyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ReleasePolicy {
		return vs[0].([]*ReleasePolicy)[vs[1].(int)]
	}).(ReleasePolicyOutput)
}

type ReleasePolicyMapOutput struct{ *pulumi.OutputState }

func (ReleasePolicyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ReleasePolicy)(nil)).Elem()
}

func (o ReleasePolicyMapOutput) ToReleasePolicyMapOutput() ReleasePolicyMapOutput {
	return o
}

func (o ReleasePolicyMapOutput) ToReleasePolicyMapOutputWithContext(ctx context.Context) ReleasePolicyMapOutput {
	return o
}

func (o ReleasePolicyMapOutput) MapIndex(k pulumi.StringInput) ReleasePolicyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ReleasePolicy {
		return vs[0].(map[string]*ReleasePolicy)[vs[1].(string)]
	}).(ReleasePolicyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ReleasePolicyInput)(nil)).Elem(), &ReleasePolicy{})
	pulumi.RegisterInputType(reflect.TypeOf((*ReleasePolicyArrayInput)(nil)).Elem(), ReleasePolicyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ReleasePolicyMapInput)(nil)).Elem(), ReleasePolicyMap{})
	pulumi.RegisterOutputType(ReleasePolicyOutput{})
	pulumi.RegisterOutputType(ReleasePolicyArrayOutput{})
	pulumi.RegisterOutputType(ReleasePolicyMapOutput{})
}
