# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['AiToolArgs', 'AiTool']

@pulumi.input_type
class AiToolArgs:
    def __init__(__self__, *,
                 key: pulumi.Input[_builtins.str],
                 project_key: pulumi.Input[_builtins.str],
                 schema_json: pulumi.Input[_builtins.str],
                 custom_parameters: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 maintainer_id: Optional[pulumi.Input[_builtins.str]] = None,
                 maintainer_team_key: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a AiTool resource.

        :param pulumi.Input[_builtins.str] key: The AI tool's unique key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.str] project_key: The project key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.str] schema_json: A JSON string representing the JSON Schema for the tool's parameters.
        :param pulumi.Input[_builtins.str] custom_parameters: A JSON string representing custom application-level metadata for the AI tool.
        :param pulumi.Input[_builtins.str] description: The AI tool's description.
        :param pulumi.Input[_builtins.str] maintainer_id: The member ID of the maintainer for this AI tool. Conflicts with `maintainer_team_key`.
        :param pulumi.Input[_builtins.str] maintainer_team_key: The team key of the maintainer team for this AI tool. Conflicts with `maintainer_id`.
        """
        pulumi.set(__self__, "key", key)
        pulumi.set(__self__, "project_key", project_key)
        pulumi.set(__self__, "schema_json", schema_json)
        if custom_parameters is not None:
            pulumi.set(__self__, "custom_parameters", custom_parameters)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if maintainer_id is not None:
            pulumi.set(__self__, "maintainer_id", maintainer_id)
        if maintainer_team_key is not None:
            pulumi.set(__self__, "maintainer_team_key", maintainer_team_key)

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Input[_builtins.str]:
        """
        The AI tool's unique key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter(name="projectKey")
    def project_key(self) -> pulumi.Input[_builtins.str]:
        """
        The project key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        """
        return pulumi.get(self, "project_key")

    @project_key.setter
    def project_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_key", value)

    @_builtins.property
    @pulumi.getter(name="schemaJson")
    def schema_json(self) -> pulumi.Input[_builtins.str]:
        """
        A JSON string representing the JSON Schema for the tool's parameters.
        """
        return pulumi.get(self, "schema_json")

    @schema_json.setter
    def schema_json(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "schema_json", value)

    @_builtins.property
    @pulumi.getter(name="customParameters")
    def custom_parameters(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A JSON string representing custom application-level metadata for the AI tool.
        """
        return pulumi.get(self, "custom_parameters")

    @custom_parameters.setter
    def custom_parameters(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "custom_parameters", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The AI tool's description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="maintainerId")
    def maintainer_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The member ID of the maintainer for this AI tool. Conflicts with `maintainer_team_key`.
        """
        return pulumi.get(self, "maintainer_id")

    @maintainer_id.setter
    def maintainer_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "maintainer_id", value)

    @_builtins.property
    @pulumi.getter(name="maintainerTeamKey")
    def maintainer_team_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The team key of the maintainer team for this AI tool. Conflicts with `maintainer_id`.
        """
        return pulumi.get(self, "maintainer_team_key")

    @maintainer_team_key.setter
    def maintainer_team_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "maintainer_team_key", value)


@pulumi.input_type
class _AiToolState:
    def __init__(__self__, *,
                 creation_date: Optional[pulumi.Input[_builtins.int]] = None,
                 custom_parameters: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 maintainer_id: Optional[pulumi.Input[_builtins.str]] = None,
                 maintainer_team_key: Optional[pulumi.Input[_builtins.str]] = None,
                 project_key: Optional[pulumi.Input[_builtins.str]] = None,
                 schema_json: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.int]] = None):
        """
        Input properties used for looking up and filtering AiTool resources.

        :param pulumi.Input[_builtins.int] creation_date: The creation timestamp of the AI tool.
        :param pulumi.Input[_builtins.str] custom_parameters: A JSON string representing custom application-level metadata for the AI tool.
        :param pulumi.Input[_builtins.str] description: The AI tool's description.
        :param pulumi.Input[_builtins.str] key: The AI tool's unique key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.str] maintainer_id: The member ID of the maintainer for this AI tool. Conflicts with `maintainer_team_key`.
        :param pulumi.Input[_builtins.str] maintainer_team_key: The team key of the maintainer team for this AI tool. Conflicts with `maintainer_id`.
        :param pulumi.Input[_builtins.str] project_key: The project key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.str] schema_json: A JSON string representing the JSON Schema for the tool's parameters.
        :param pulumi.Input[_builtins.int] version: The version of the AI tool.
        """
        if creation_date is not None:
            pulumi.set(__self__, "creation_date", creation_date)
        if custom_parameters is not None:
            pulumi.set(__self__, "custom_parameters", custom_parameters)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if maintainer_id is not None:
            pulumi.set(__self__, "maintainer_id", maintainer_id)
        if maintainer_team_key is not None:
            pulumi.set(__self__, "maintainer_team_key", maintainer_team_key)
        if project_key is not None:
            pulumi.set(__self__, "project_key", project_key)
        if schema_json is not None:
            pulumi.set(__self__, "schema_json", schema_json)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter(name="creationDate")
    def creation_date(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The creation timestamp of the AI tool.
        """
        return pulumi.get(self, "creation_date")

    @creation_date.setter
    def creation_date(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "creation_date", value)

    @_builtins.property
    @pulumi.getter(name="customParameters")
    def custom_parameters(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A JSON string representing custom application-level metadata for the AI tool.
        """
        return pulumi.get(self, "custom_parameters")

    @custom_parameters.setter
    def custom_parameters(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "custom_parameters", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The AI tool's description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The AI tool's unique key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter(name="maintainerId")
    def maintainer_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The member ID of the maintainer for this AI tool. Conflicts with `maintainer_team_key`.
        """
        return pulumi.get(self, "maintainer_id")

    @maintainer_id.setter
    def maintainer_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "maintainer_id", value)

    @_builtins.property
    @pulumi.getter(name="maintainerTeamKey")
    def maintainer_team_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The team key of the maintainer team for this AI tool. Conflicts with `maintainer_id`.
        """
        return pulumi.get(self, "maintainer_team_key")

    @maintainer_team_key.setter
    def maintainer_team_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "maintainer_team_key", value)

    @_builtins.property
    @pulumi.getter(name="projectKey")
    def project_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The project key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        """
        return pulumi.get(self, "project_key")

    @project_key.setter
    def project_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "project_key", value)

    @_builtins.property
    @pulumi.getter(name="schemaJson")
    def schema_json(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A JSON string representing the JSON Schema for the tool's parameters.
        """
        return pulumi.get(self, "schema_json")

    @schema_json.setter
    def schema_json(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "schema_json", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The version of the AI tool.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "version", value)


@pulumi.type_token("launchdarkly:index/aiTool:AiTool")
class AiTool(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 custom_parameters: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 maintainer_id: Optional[pulumi.Input[_builtins.str]] = None,
                 maintainer_team_key: Optional[pulumi.Input[_builtins.str]] = None,
                 project_key: Optional[pulumi.Input[_builtins.str]] = None,
                 schema_json: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Provides a LaunchDarkly AI tool resource.

        This resource allows you to create and manage AI tools within your LaunchDarkly project.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_launchdarkly as launchdarkly

        example = launchdarkly.AiTool("example",
            project_key=example_launchdarkly_project["key"],
            key="web-search",
            description="Search the web for information",
            schema_json=json.dumps({
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The search query",
                    },
                },
                "required": ["query"],
            }))
        ```

        ## Import

        LaunchDarkly AI tools can be imported using the format `project_key/tool_key`

        ```sh
        $ pulumi import launchdarkly:index/aiTool:AiTool example example-project/web-search
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] custom_parameters: A JSON string representing custom application-level metadata for the AI tool.
        :param pulumi.Input[_builtins.str] description: The AI tool's description.
        :param pulumi.Input[_builtins.str] key: The AI tool's unique key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.str] maintainer_id: The member ID of the maintainer for this AI tool. Conflicts with `maintainer_team_key`.
        :param pulumi.Input[_builtins.str] maintainer_team_key: The team key of the maintainer team for this AI tool. Conflicts with `maintainer_id`.
        :param pulumi.Input[_builtins.str] project_key: The project key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.str] schema_json: A JSON string representing the JSON Schema for the tool's parameters.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AiToolArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Provides a LaunchDarkly AI tool resource.

        This resource allows you to create and manage AI tools within your LaunchDarkly project.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_launchdarkly as launchdarkly

        example = launchdarkly.AiTool("example",
            project_key=example_launchdarkly_project["key"],
            key="web-search",
            description="Search the web for information",
            schema_json=json.dumps({
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The search query",
                    },
                },
                "required": ["query"],
            }))
        ```

        ## Import

        LaunchDarkly AI tools can be imported using the format `project_key/tool_key`

        ```sh
        $ pulumi import launchdarkly:index/aiTool:AiTool example example-project/web-search
        ```


        :param str resource_name: The name of the resource.
        :param AiToolArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AiToolArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 custom_parameters: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 maintainer_id: Optional[pulumi.Input[_builtins.str]] = None,
                 maintainer_team_key: Optional[pulumi.Input[_builtins.str]] = None,
                 project_key: Optional[pulumi.Input[_builtins.str]] = None,
                 schema_json: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AiToolArgs.__new__(AiToolArgs)

            __props__.__dict__["custom_parameters"] = custom_parameters
            __props__.__dict__["description"] = description
            if key is None and not opts.urn:
                raise TypeError("Missing required property 'key'")
            __props__.__dict__["key"] = key
            __props__.__dict__["maintainer_id"] = maintainer_id
            __props__.__dict__["maintainer_team_key"] = maintainer_team_key
            if project_key is None and not opts.urn:
                raise TypeError("Missing required property 'project_key'")
            __props__.__dict__["project_key"] = project_key
            if schema_json is None and not opts.urn:
                raise TypeError("Missing required property 'schema_json'")
            __props__.__dict__["schema_json"] = schema_json
            __props__.__dict__["creation_date"] = None
            __props__.__dict__["version"] = None
        super(AiTool, __self__).__init__(
            'launchdarkly:index/aiTool:AiTool',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            creation_date: Optional[pulumi.Input[_builtins.int]] = None,
            custom_parameters: Optional[pulumi.Input[_builtins.str]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            key: Optional[pulumi.Input[_builtins.str]] = None,
            maintainer_id: Optional[pulumi.Input[_builtins.str]] = None,
            maintainer_team_key: Optional[pulumi.Input[_builtins.str]] = None,
            project_key: Optional[pulumi.Input[_builtins.str]] = None,
            schema_json: Optional[pulumi.Input[_builtins.str]] = None,
            version: Optional[pulumi.Input[_builtins.int]] = None) -> 'AiTool':
        """
        Get an existing AiTool resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] creation_date: The creation timestamp of the AI tool.
        :param pulumi.Input[_builtins.str] custom_parameters: A JSON string representing custom application-level metadata for the AI tool.
        :param pulumi.Input[_builtins.str] description: The AI tool's description.
        :param pulumi.Input[_builtins.str] key: The AI tool's unique key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.str] maintainer_id: The member ID of the maintainer for this AI tool. Conflicts with `maintainer_team_key`.
        :param pulumi.Input[_builtins.str] maintainer_team_key: The team key of the maintainer team for this AI tool. Conflicts with `maintainer_id`.
        :param pulumi.Input[_builtins.str] project_key: The project key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.str] schema_json: A JSON string representing the JSON Schema for the tool's parameters.
        :param pulumi.Input[_builtins.int] version: The version of the AI tool.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AiToolState.__new__(_AiToolState)

        __props__.__dict__["creation_date"] = creation_date
        __props__.__dict__["custom_parameters"] = custom_parameters
        __props__.__dict__["description"] = description
        __props__.__dict__["key"] = key
        __props__.__dict__["maintainer_id"] = maintainer_id
        __props__.__dict__["maintainer_team_key"] = maintainer_team_key
        __props__.__dict__["project_key"] = project_key
        __props__.__dict__["schema_json"] = schema_json
        __props__.__dict__["version"] = version
        return AiTool(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="creationDate")
    def creation_date(self) -> pulumi.Output[_builtins.int]:
        """
        The creation timestamp of the AI tool.
        """
        return pulumi.get(self, "creation_date")

    @_builtins.property
    @pulumi.getter(name="customParameters")
    def custom_parameters(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A JSON string representing custom application-level metadata for the AI tool.
        """
        return pulumi.get(self, "custom_parameters")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The AI tool's description.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Output[_builtins.str]:
        """
        The AI tool's unique key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter(name="maintainerId")
    def maintainer_id(self) -> pulumi.Output[_builtins.str]:
        """
        The member ID of the maintainer for this AI tool. Conflicts with `maintainer_team_key`.
        """
        return pulumi.get(self, "maintainer_id")

    @_builtins.property
    @pulumi.getter(name="maintainerTeamKey")
    def maintainer_team_key(self) -> pulumi.Output[_builtins.str]:
        """
        The team key of the maintainer team for this AI tool. Conflicts with `maintainer_id`.
        """
        return pulumi.get(self, "maintainer_team_key")

    @_builtins.property
    @pulumi.getter(name="projectKey")
    def project_key(self) -> pulumi.Output[_builtins.str]:
        """
        The project key. A change in this field will force the destruction of the existing resource and the creation of a new one.
        """
        return pulumi.get(self, "project_key")

    @_builtins.property
    @pulumi.getter(name="schemaJson")
    def schema_json(self) -> pulumi.Output[_builtins.str]:
        """
        A JSON string representing the JSON Schema for the tool's parameters.
        """
        return pulumi.get(self, "schema_json")

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Output[_builtins.int]:
        """
        The version of the AI tool.
        """
        return pulumi.get(self, "version")

