# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetRelayProxyConfigurationResult',
    'AwaitableGetRelayProxyConfigurationResult',
    'get_relay_proxy_configuration',
    'get_relay_proxy_configuration_output',
]

@pulumi.output_type
class GetRelayProxyConfigurationResult:
    """
    A collection of values returned by getRelayProxyConfiguration.
    """
    def __init__(__self__, display_key=None, id=None, name=None, policies=None):
        if display_key and not isinstance(display_key, str):
            raise TypeError("Expected argument 'display_key' to be a str")
        pulumi.set(__self__, "display_key", display_key)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if policies and not isinstance(policies, list):
            raise TypeError("Expected argument 'policies' to be a list")
        pulumi.set(__self__, "policies", policies)

    @_builtins.property
    @pulumi.getter(name="displayKey")
    def display_key(self) -> _builtins.str:
        """
        The last 4 characters of the Relay Proxy configuration's unique key.
        """
        return pulumi.get(self, "display_key")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The Relay Proxy configuration's unique 24 character ID. The unique relay proxy ID can be found in the relay proxy edit page URL, which you can locate by clicking the three dot menu on your relay proxy item in the UI and selecting "Edit configuration":
        `
        https://app.launchdarkly.com/settings/relay/THIS_IS_YOUR_RELAY_PROXY_ID/edit
        `
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The human-readable name for your Relay Proxy configuration.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def policies(self) -> Sequence['outputs.GetRelayProxyConfigurationPolicyResult']:
        """
        The Relay Proxy configuration's rule policy block. This determines what content the Relay Proxy receives. To learn more, read [Understanding policies](https://docs.launchdarkly.com/home/members/role-policies#understanding-policies).
        """
        return pulumi.get(self, "policies")


class AwaitableGetRelayProxyConfigurationResult(GetRelayProxyConfigurationResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetRelayProxyConfigurationResult(
            display_key=self.display_key,
            id=self.id,
            name=self.name,
            policies=self.policies)


def get_relay_proxy_configuration(id: Optional[_builtins.str] = None,
                                  opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetRelayProxyConfigurationResult:
    """
    ## Example Usage

    ```python
    import pulumi
    import pulumi_launchdarkly as launchdarkly

    example = launchdarkly.get_relay_proxy_configuration(id="123456789abcdef123456789")
    ```


    :param _builtins.str id: The Relay Proxy configuration's unique 24 character ID. The unique relay proxy ID can be found in the relay proxy edit page URL, which you can locate by clicking the three dot menu on your relay proxy item in the UI and selecting "Edit configuration":
           `
           https://app.launchdarkly.com/settings/relay/THIS_IS_YOUR_RELAY_PROXY_ID/edit
           `
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('launchdarkly:index/getRelayProxyConfiguration:getRelayProxyConfiguration', __args__, opts=opts, typ=GetRelayProxyConfigurationResult).value

    return AwaitableGetRelayProxyConfigurationResult(
        display_key=pulumi.get(__ret__, 'display_key'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        policies=pulumi.get(__ret__, 'policies'))
def get_relay_proxy_configuration_output(id: Optional[pulumi.Input[_builtins.str]] = None,
                                         opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetRelayProxyConfigurationResult]:
    """
    ## Example Usage

    ```python
    import pulumi
    import pulumi_launchdarkly as launchdarkly

    example = launchdarkly.get_relay_proxy_configuration(id="123456789abcdef123456789")
    ```


    :param _builtins.str id: The Relay Proxy configuration's unique 24 character ID. The unique relay proxy ID can be found in the relay proxy edit page URL, which you can locate by clicking the three dot menu on your relay proxy item in the UI and selecting "Edit configuration":
           `
           https://app.launchdarkly.com/settings/relay/THIS_IS_YOUR_RELAY_PROXY_ID/edit
           `
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('launchdarkly:index/getRelayProxyConfiguration:getRelayProxyConfiguration', __args__, opts=opts, typ=GetRelayProxyConfigurationResult)
    return __ret__.apply(lambda __response__: GetRelayProxyConfigurationResult(
        display_key=pulumi.get(__response__, 'display_key'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        policies=pulumi.get(__response__, 'policies')))
