# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetAiAgentGraphResult',
    'AwaitableGetAiAgentGraphResult',
    'get_ai_agent_graph',
    'get_ai_agent_graph_output',
]

@pulumi.output_type
class GetAiAgentGraphResult:
    """
    A collection of values returned by getAiAgentGraph.
    """
    def __init__(__self__, creation_date=None, description=None, edges=None, id=None, key=None, last_modified=None, maintainer_id=None, maintainer_team_key=None, name=None, project_key=None, root_config_key=None):
        if creation_date and not isinstance(creation_date, int):
            raise TypeError("Expected argument 'creation_date' to be a int")
        pulumi.set(__self__, "creation_date", creation_date)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if edges and not isinstance(edges, dict):
            raise TypeError("Expected argument 'edges' to be a dict")
        pulumi.set(__self__, "edges", edges)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if key and not isinstance(key, str):
            raise TypeError("Expected argument 'key' to be a str")
        pulumi.set(__self__, "key", key)
        if last_modified and not isinstance(last_modified, int):
            raise TypeError("Expected argument 'last_modified' to be a int")
        pulumi.set(__self__, "last_modified", last_modified)
        if maintainer_id and not isinstance(maintainer_id, str):
            raise TypeError("Expected argument 'maintainer_id' to be a str")
        pulumi.set(__self__, "maintainer_id", maintainer_id)
        if maintainer_team_key and not isinstance(maintainer_team_key, str):
            raise TypeError("Expected argument 'maintainer_team_key' to be a str")
        pulumi.set(__self__, "maintainer_team_key", maintainer_team_key)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if project_key and not isinstance(project_key, str):
            raise TypeError("Expected argument 'project_key' to be a str")
        pulumi.set(__self__, "project_key", project_key)
        if root_config_key and not isinstance(root_config_key, str):
            raise TypeError("Expected argument 'root_config_key' to be a str")
        pulumi.set(__self__, "root_config_key", root_config_key)

    @_builtins.property
    @pulumi.getter(name="creationDate")
    def creation_date(self) -> _builtins.int:
        """
        The creation timestamp of the agent graph, in Unix epoch milliseconds.
        """
        return pulumi.get(self, "creation_date")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        A description of the agent graph.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def edges(self) -> Mapping[str, 'outputs.GetAiAgentGraphEdgesResult']:
        """
        The edges in the graph, keyed by edge key. Each edge connects a source AgentControl config to a target AgentControl config.
        """
        return pulumi.get(self, "edges")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The composite ID of the agent graph in the format `project_key/key`.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def key(self) -> _builtins.str:
        """
        The unique key of the agent graph.
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter(name="lastModified")
    def last_modified(self) -> _builtins.int:
        """
        The timestamp of the agent graph's last update, in Unix epoch milliseconds.
        """
        return pulumi.get(self, "last_modified")

    @_builtins.property
    @pulumi.getter(name="maintainerId")
    def maintainer_id(self) -> _builtins.str:
        """
        The member ID of the maintainer for this agent graph.
        """
        return pulumi.get(self, "maintainer_id")

    @_builtins.property
    @pulumi.getter(name="maintainerTeamKey")
    def maintainer_team_key(self) -> _builtins.str:
        """
        The team key of the maintainer team for this agent graph.
        """
        return pulumi.get(self, "maintainer_team_key")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        A human-readable name for the agent graph.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="projectKey")
    def project_key(self) -> _builtins.str:
        """
        The project key.
        """
        return pulumi.get(self, "project_key")

    @_builtins.property
    @pulumi.getter(name="rootConfigKey")
    def root_config_key(self) -> _builtins.str:
        """
        The AgentControl config key of the root node of the graph.
        """
        return pulumi.get(self, "root_config_key")


class AwaitableGetAiAgentGraphResult(GetAiAgentGraphResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAiAgentGraphResult(
            creation_date=self.creation_date,
            description=self.description,
            edges=self.edges,
            id=self.id,
            key=self.key,
            last_modified=self.last_modified,
            maintainer_id=self.maintainer_id,
            maintainer_team_key=self.maintainer_team_key,
            name=self.name,
            project_key=self.project_key,
            root_config_key=self.root_config_key)


def get_ai_agent_graph(key: Optional[_builtins.str] = None,
                       project_key: Optional[_builtins.str] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAiAgentGraphResult:
    """
    Provides a LaunchDarkly AI agent graph data source.

    This data source allows you to retrieve information about an agent graph, a directed graph of AgentControl configs, in your LaunchDarkly project.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_launchdarkly as launchdarkly

    support_workflow = launchdarkly.get_ai_agent_graph(project_key="example-project",
        key="support-workflow")
    ```


    :param _builtins.str key: The unique key of the agent graph.
    :param _builtins.str project_key: The project key.
    """
    __args__ = dict()
    __args__['key'] = key
    __args__['projectKey'] = project_key
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('launchdarkly:index/getAiAgentGraph:getAiAgentGraph', __args__, opts=opts, typ=GetAiAgentGraphResult).value

    return AwaitableGetAiAgentGraphResult(
        creation_date=pulumi.get(__ret__, 'creation_date'),
        description=pulumi.get(__ret__, 'description'),
        edges=pulumi.get(__ret__, 'edges'),
        id=pulumi.get(__ret__, 'id'),
        key=pulumi.get(__ret__, 'key'),
        last_modified=pulumi.get(__ret__, 'last_modified'),
        maintainer_id=pulumi.get(__ret__, 'maintainer_id'),
        maintainer_team_key=pulumi.get(__ret__, 'maintainer_team_key'),
        name=pulumi.get(__ret__, 'name'),
        project_key=pulumi.get(__ret__, 'project_key'),
        root_config_key=pulumi.get(__ret__, 'root_config_key'))
def get_ai_agent_graph_output(key: pulumi.Input[Optional[_builtins.str]] = None,
                              project_key: pulumi.Input[Optional[_builtins.str]] = None,
                              opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAiAgentGraphResult]:
    """
    Provides a LaunchDarkly AI agent graph data source.

    This data source allows you to retrieve information about an agent graph, a directed graph of AgentControl configs, in your LaunchDarkly project.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_launchdarkly as launchdarkly

    support_workflow = launchdarkly.get_ai_agent_graph(project_key="example-project",
        key="support-workflow")
    ```


    :param _builtins.str key: The unique key of the agent graph.
    :param _builtins.str project_key: The project key.
    """
    __args__ = dict()
    __args__['key'] = key
    __args__['projectKey'] = project_key
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('launchdarkly:index/getAiAgentGraph:getAiAgentGraph', __args__, opts=opts, typ=GetAiAgentGraphResult)
    return __ret__.apply(lambda __response__: GetAiAgentGraphResult(
        creation_date=pulumi.get(__response__, 'creation_date'),
        description=pulumi.get(__response__, 'description'),
        edges=pulumi.get(__response__, 'edges'),
        id=pulumi.get(__response__, 'id'),
        key=pulumi.get(__response__, 'key'),
        last_modified=pulumi.get(__response__, 'last_modified'),
        maintainer_id=pulumi.get(__response__, 'maintainer_id'),
        maintainer_team_key=pulumi.get(__response__, 'maintainer_team_key'),
        name=pulumi.get(__response__, 'name'),
        project_key=pulumi.get(__response__, 'project_key'),
        root_config_key=pulumi.get(__response__, 'root_config_key')))
