# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetModelConfigResult',
    'AwaitableGetModelConfigResult',
    'get_model_config',
    'get_model_config_output',
]

@pulumi.output_type
class GetModelConfigResult:
    """
    A collection of values returned by getModelConfig.
    """
    def __init__(__self__, cost_per_input_token=None, cost_per_output_token=None, custom_parameters=None, global_=None, icon=None, id=None, key=None, model_id=None, model_provider=None, name=None, params=None, project_key=None, tags=None, version=None):
        if cost_per_input_token and not isinstance(cost_per_input_token, float):
            raise TypeError("Expected argument 'cost_per_input_token' to be a float")
        pulumi.set(__self__, "cost_per_input_token", cost_per_input_token)
        if cost_per_output_token and not isinstance(cost_per_output_token, float):
            raise TypeError("Expected argument 'cost_per_output_token' to be a float")
        pulumi.set(__self__, "cost_per_output_token", cost_per_output_token)
        if custom_parameters and not isinstance(custom_parameters, str):
            raise TypeError("Expected argument 'custom_parameters' to be a str")
        pulumi.set(__self__, "custom_parameters", custom_parameters)
        if global_ and not isinstance(global_, bool):
            raise TypeError("Expected argument 'global_' to be a bool")
        pulumi.set(__self__, "global_", global_)
        if icon and not isinstance(icon, str):
            raise TypeError("Expected argument 'icon' to be a str")
        pulumi.set(__self__, "icon", icon)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if key and not isinstance(key, str):
            raise TypeError("Expected argument 'key' to be a str")
        pulumi.set(__self__, "key", key)
        if model_id and not isinstance(model_id, str):
            raise TypeError("Expected argument 'model_id' to be a str")
        pulumi.set(__self__, "model_id", model_id)
        if model_provider and not isinstance(model_provider, str):
            raise TypeError("Expected argument 'model_provider' to be a str")
        pulumi.set(__self__, "model_provider", model_provider)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if params and not isinstance(params, str):
            raise TypeError("Expected argument 'params' to be a str")
        pulumi.set(__self__, "params", params)
        if project_key and not isinstance(project_key, str):
            raise TypeError("Expected argument 'project_key' to be a str")
        pulumi.set(__self__, "project_key", project_key)
        if tags and not isinstance(tags, list):
            raise TypeError("Expected argument 'tags' to be a list")
        pulumi.set(__self__, "tags", tags)
        if version and not isinstance(version, int):
            raise TypeError("Expected argument 'version' to be a int")
        pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter(name="costPerInputToken")
    def cost_per_input_token(self) -> _builtins.float:
        """
        The cost per input token for the model.
        """
        return pulumi.get(self, "cost_per_input_token")

    @_builtins.property
    @pulumi.getter(name="costPerOutputToken")
    def cost_per_output_token(self) -> _builtins.float:
        """
        The cost per output token for the model.
        """
        return pulumi.get(self, "cost_per_output_token")

    @_builtins.property
    @pulumi.getter(name="customParameters")
    def custom_parameters(self) -> _builtins.str:
        """
        A JSON string representing custom parameters for the model config.
        """
        return pulumi.get(self, "custom_parameters")

    @_builtins.property
    @pulumi.getter(name="global")
    def global_(self) -> _builtins.bool:
        """
        Whether the model config is available globally.
        """
        return pulumi.get(self, "global_")

    @_builtins.property
    @pulumi.getter
    def icon(self) -> _builtins.str:
        """
        The icon for the model config.
        """
        return pulumi.get(self, "icon")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def key(self) -> _builtins.str:
        """
        The model config's unique key.
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter(name="modelId")
    def model_id(self) -> _builtins.str:
        """
        The model identifier (e.g. `gpt-4`, `claude-3`).
        """
        return pulumi.get(self, "model_id")

    @_builtins.property
    @pulumi.getter(name="modelProvider")
    def model_provider(self) -> _builtins.str:
        """
        The provider name for the model config (e.g. `openai`, `anthropic`).
        """
        return pulumi.get(self, "model_provider")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The model config's human-readable name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def params(self) -> _builtins.str:
        """
        A JSON string representing the model parameters (e.g. `{"temperature": 0.7, "maxTokens": 4096}`).
        """
        return pulumi.get(self, "params")

    @_builtins.property
    @pulumi.getter(name="projectKey")
    def project_key(self) -> _builtins.str:
        """
        The project key.
        """
        return pulumi.get(self, "project_key")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Sequence[_builtins.str]:
        """
        Tags associated with your resource.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.int:
        """
        The version of the model config.
        """
        return pulumi.get(self, "version")


class AwaitableGetModelConfigResult(GetModelConfigResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetModelConfigResult(
            cost_per_input_token=self.cost_per_input_token,
            cost_per_output_token=self.cost_per_output_token,
            custom_parameters=self.custom_parameters,
            global_=self.global_,
            icon=self.icon,
            id=self.id,
            key=self.key,
            model_id=self.model_id,
            model_provider=self.model_provider,
            name=self.name,
            params=self.params,
            project_key=self.project_key,
            tags=self.tags,
            version=self.version)


def get_model_config(key: Optional[_builtins.str] = None,
                     project_key: Optional[_builtins.str] = None,
                     opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetModelConfigResult:
    """
    Provides a LaunchDarkly model config data source.

    This data source allows you to retrieve AI model configuration information from your LaunchDarkly project.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_launchdarkly as launchdarkly

    example = launchdarkly.get_model_config(key="gpt-4-turbo",
        project_key="example-project")
    ```


    :param _builtins.str key: The model config's unique key.
    :param _builtins.str project_key: The project key.
    """
    __args__ = dict()
    __args__['key'] = key
    __args__['projectKey'] = project_key
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('launchdarkly:index/getModelConfig:getModelConfig', __args__, opts=opts, typ=GetModelConfigResult).value

    return AwaitableGetModelConfigResult(
        cost_per_input_token=pulumi.get(__ret__, 'cost_per_input_token'),
        cost_per_output_token=pulumi.get(__ret__, 'cost_per_output_token'),
        custom_parameters=pulumi.get(__ret__, 'custom_parameters'),
        global_=pulumi.get(__ret__, 'global_'),
        icon=pulumi.get(__ret__, 'icon'),
        id=pulumi.get(__ret__, 'id'),
        key=pulumi.get(__ret__, 'key'),
        model_id=pulumi.get(__ret__, 'model_id'),
        model_provider=pulumi.get(__ret__, 'model_provider'),
        name=pulumi.get(__ret__, 'name'),
        params=pulumi.get(__ret__, 'params'),
        project_key=pulumi.get(__ret__, 'project_key'),
        tags=pulumi.get(__ret__, 'tags'),
        version=pulumi.get(__ret__, 'version'))
def get_model_config_output(key: Optional[pulumi.Input[_builtins.str]] = None,
                            project_key: Optional[pulumi.Input[_builtins.str]] = None,
                            opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetModelConfigResult]:
    """
    Provides a LaunchDarkly model config data source.

    This data source allows you to retrieve AI model configuration information from your LaunchDarkly project.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_launchdarkly as launchdarkly

    example = launchdarkly.get_model_config(key="gpt-4-turbo",
        project_key="example-project")
    ```


    :param _builtins.str key: The model config's unique key.
    :param _builtins.str project_key: The project key.
    """
    __args__ = dict()
    __args__['key'] = key
    __args__['projectKey'] = project_key
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('launchdarkly:index/getModelConfig:getModelConfig', __args__, opts=opts, typ=GetModelConfigResult)
    return __ret__.apply(lambda __response__: GetModelConfigResult(
        cost_per_input_token=pulumi.get(__response__, 'cost_per_input_token'),
        cost_per_output_token=pulumi.get(__response__, 'cost_per_output_token'),
        custom_parameters=pulumi.get(__response__, 'custom_parameters'),
        global_=pulumi.get(__response__, 'global_'),
        icon=pulumi.get(__response__, 'icon'),
        id=pulumi.get(__response__, 'id'),
        key=pulumi.get(__response__, 'key'),
        model_id=pulumi.get(__response__, 'model_id'),
        model_provider=pulumi.get(__response__, 'model_provider'),
        name=pulumi.get(__response__, 'name'),
        params=pulumi.get(__response__, 'params'),
        project_key=pulumi.get(__response__, 'project_key'),
        tags=pulumi.get(__response__, 'tags'),
        version=pulumi.get(__response__, 'version')))
