# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ReleasePolicyArgs', 'ReleasePolicy']

@pulumi.input_type
class ReleasePolicyArgs:
    def __init__(__self__, *,
                 key: pulumi.Input[_builtins.str],
                 project_key: pulumi.Input[_builtins.str],
                 release_method: pulumi.Input[_builtins.str],
                 guarded_release_config: pulumi.Input[Optional['ReleasePolicyGuardedReleaseConfigArgs']] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 progressive_release_config: pulumi.Input[Optional['ReleasePolicyProgressiveReleaseConfigArgs']] = None,
                 scope: pulumi.Input[Optional['ReleasePolicyScopeArgs']] = None):
        """
        The set of arguments for constructing a ReleasePolicy resource.

        :param pulumi.Input[_builtins.str] key: The unique human-readable key that references the release policy. A change in this field forces the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.str] project_key: The release policy's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.str] release_method: The release method this policy uses. Must be one of `guarded-release` or `progressive-release`. Set `guarded_release_config` for a `guarded-release` and `progressive_release_config` for a `progressive-release`.
        :param pulumi.Input['ReleasePolicyGuardedReleaseConfigArgs'] guarded_release_config: Configuration for a `guarded-release`. May only be set when `release_method` is `guarded-release`.
        :param pulumi.Input[_builtins.str] name: The human-friendly name for the release policy.
        :param pulumi.Input['ReleasePolicyProgressiveReleaseConfigArgs'] progressive_release_config: Configuration for a `progressive-release`. May only be set when `release_method` is `progressive-release`.
        :param pulumi.Input['ReleasePolicyScopeArgs'] scope: The scope that determines which environments and flags this release policy applies to.
        """
        pulumi.set(__self__, "key", key)
        pulumi.set(__self__, "project_key", project_key)
        pulumi.set(__self__, "release_method", release_method)
        if guarded_release_config is not None:
            pulumi.set(__self__, "guarded_release_config", guarded_release_config)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if progressive_release_config is not None:
            pulumi.set(__self__, "progressive_release_config", progressive_release_config)
        if scope is not None:
            pulumi.set(__self__, "scope", scope)

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Input[_builtins.str]:
        """
        The unique human-readable key that references the release policy. A change in this field forces the destruction of the existing resource and the creation of a new one.
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter(name="projectKey")
    def project_key(self) -> pulumi.Input[_builtins.str]:
        """
        The release policy's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
        """
        return pulumi.get(self, "project_key")

    @project_key.setter
    def project_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_key", value)

    @_builtins.property
    @pulumi.getter(name="releaseMethod")
    def release_method(self) -> pulumi.Input[_builtins.str]:
        """
        The release method this policy uses. Must be one of `guarded-release` or `progressive-release`. Set `guarded_release_config` for a `guarded-release` and `progressive_release_config` for a `progressive-release`.
        """
        return pulumi.get(self, "release_method")

    @release_method.setter
    def release_method(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "release_method", value)

    @_builtins.property
    @pulumi.getter(name="guardedReleaseConfig")
    def guarded_release_config(self) -> pulumi.Input[Optional['ReleasePolicyGuardedReleaseConfigArgs']]:
        """
        Configuration for a `guarded-release`. May only be set when `release_method` is `guarded-release`.
        """
        return pulumi.get(self, "guarded_release_config")

    @guarded_release_config.setter
    def guarded_release_config(self, value: pulumi.Input[Optional['ReleasePolicyGuardedReleaseConfigArgs']]):
        pulumi.set(self, "guarded_release_config", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The human-friendly name for the release policy.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="progressiveReleaseConfig")
    def progressive_release_config(self) -> pulumi.Input[Optional['ReleasePolicyProgressiveReleaseConfigArgs']]:
        """
        Configuration for a `progressive-release`. May only be set when `release_method` is `progressive-release`.
        """
        return pulumi.get(self, "progressive_release_config")

    @progressive_release_config.setter
    def progressive_release_config(self, value: pulumi.Input[Optional['ReleasePolicyProgressiveReleaseConfigArgs']]):
        pulumi.set(self, "progressive_release_config", value)

    @_builtins.property
    @pulumi.getter
    def scope(self) -> pulumi.Input[Optional['ReleasePolicyScopeArgs']]:
        """
        The scope that determines which environments and flags this release policy applies to.
        """
        return pulumi.get(self, "scope")

    @scope.setter
    def scope(self, value: pulumi.Input[Optional['ReleasePolicyScopeArgs']]):
        pulumi.set(self, "scope", value)


@pulumi.input_type
class _ReleasePolicyState:
    def __init__(__self__, *,
                 guarded_release_config: pulumi.Input[Optional['ReleasePolicyGuardedReleaseConfigArgs']] = None,
                 key: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 progressive_release_config: pulumi.Input[Optional['ReleasePolicyProgressiveReleaseConfigArgs']] = None,
                 project_key: pulumi.Input[Optional[_builtins.str]] = None,
                 rank: pulumi.Input[Optional[_builtins.int]] = None,
                 release_method: pulumi.Input[Optional[_builtins.str]] = None,
                 scope: pulumi.Input[Optional['ReleasePolicyScopeArgs']] = None):
        """
        Input properties used for looking up and filtering ReleasePolicy resources.

        :param pulumi.Input['ReleasePolicyGuardedReleaseConfigArgs'] guarded_release_config: Configuration for a `guarded-release`. May only be set when `release_method` is `guarded-release`.
        :param pulumi.Input[_builtins.str] key: The unique human-readable key that references the release policy. A change in this field forces the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.str] name: The human-friendly name for the release policy.
        :param pulumi.Input['ReleasePolicyProgressiveReleaseConfigArgs'] progressive_release_config: Configuration for a `progressive-release`. May only be set when `release_method` is `progressive-release`.
        :param pulumi.Input[_builtins.str] project_key: The release policy's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.int] rank: The rank of the release policy within the project. LaunchDarkly assigns and orders the rank. Reorder release policies in the LaunchDarkly UI.
        :param pulumi.Input[_builtins.str] release_method: The release method this policy uses. Must be one of `guarded-release` or `progressive-release`. Set `guarded_release_config` for a `guarded-release` and `progressive_release_config` for a `progressive-release`.
        :param pulumi.Input['ReleasePolicyScopeArgs'] scope: The scope that determines which environments and flags this release policy applies to.
        """
        if guarded_release_config is not None:
            pulumi.set(__self__, "guarded_release_config", guarded_release_config)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if progressive_release_config is not None:
            pulumi.set(__self__, "progressive_release_config", progressive_release_config)
        if project_key is not None:
            pulumi.set(__self__, "project_key", project_key)
        if rank is not None:
            pulumi.set(__self__, "rank", rank)
        if release_method is not None:
            pulumi.set(__self__, "release_method", release_method)
        if scope is not None:
            pulumi.set(__self__, "scope", scope)

    @_builtins.property
    @pulumi.getter(name="guardedReleaseConfig")
    def guarded_release_config(self) -> pulumi.Input[Optional['ReleasePolicyGuardedReleaseConfigArgs']]:
        """
        Configuration for a `guarded-release`. May only be set when `release_method` is `guarded-release`.
        """
        return pulumi.get(self, "guarded_release_config")

    @guarded_release_config.setter
    def guarded_release_config(self, value: pulumi.Input[Optional['ReleasePolicyGuardedReleaseConfigArgs']]):
        pulumi.set(self, "guarded_release_config", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The unique human-readable key that references the release policy. A change in this field forces the destruction of the existing resource and the creation of a new one.
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The human-friendly name for the release policy.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="progressiveReleaseConfig")
    def progressive_release_config(self) -> pulumi.Input[Optional['ReleasePolicyProgressiveReleaseConfigArgs']]:
        """
        Configuration for a `progressive-release`. May only be set when `release_method` is `progressive-release`.
        """
        return pulumi.get(self, "progressive_release_config")

    @progressive_release_config.setter
    def progressive_release_config(self, value: pulumi.Input[Optional['ReleasePolicyProgressiveReleaseConfigArgs']]):
        pulumi.set(self, "progressive_release_config", value)

    @_builtins.property
    @pulumi.getter(name="projectKey")
    def project_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The release policy's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
        """
        return pulumi.get(self, "project_key")

    @project_key.setter
    def project_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_key", value)

    @_builtins.property
    @pulumi.getter
    def rank(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The rank of the release policy within the project. LaunchDarkly assigns and orders the rank. Reorder release policies in the LaunchDarkly UI.
        """
        return pulumi.get(self, "rank")

    @rank.setter
    def rank(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "rank", value)

    @_builtins.property
    @pulumi.getter(name="releaseMethod")
    def release_method(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The release method this policy uses. Must be one of `guarded-release` or `progressive-release`. Set `guarded_release_config` for a `guarded-release` and `progressive_release_config` for a `progressive-release`.
        """
        return pulumi.get(self, "release_method")

    @release_method.setter
    def release_method(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "release_method", value)

    @_builtins.property
    @pulumi.getter
    def scope(self) -> pulumi.Input[Optional['ReleasePolicyScopeArgs']]:
        """
        The scope that determines which environments and flags this release policy applies to.
        """
        return pulumi.get(self, "scope")

    @scope.setter
    def scope(self, value: pulumi.Input[Optional['ReleasePolicyScopeArgs']]):
        pulumi.set(self, "scope", value)


@pulumi.type_token("launchdarkly:index/releasePolicy:ReleasePolicy")
class ReleasePolicy(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 guarded_release_config: pulumi.Input[Optional[Union['ReleasePolicyGuardedReleaseConfigArgs', 'ReleasePolicyGuardedReleaseConfigArgsDict']]] = None,
                 key: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 progressive_release_config: pulumi.Input[Optional[Union['ReleasePolicyProgressiveReleaseConfigArgs', 'ReleasePolicyProgressiveReleaseConfigArgsDict']]] = None,
                 project_key: pulumi.Input[Optional[_builtins.str]] = None,
                 release_method: pulumi.Input[Optional[_builtins.str]] = None,
                 scope: pulumi.Input[Optional[Union['ReleasePolicyScopeArgs', 'ReleasePolicyScopeArgsDict']]] = None,
                 __props__=None):
        """
        Provides a LaunchDarkly release policy resource.

        > **Beta:** This resource wraps a beta LaunchDarkly API (the `release-policies` endpoints, accessed with the `LD-API-Version: beta` header). Beta resources may change or be removed in future versions.

        This resource lets you create and manage [release policies](https://launchdarkly.com/docs/home/releases/release-policies) within a LaunchDarkly project. A release policy defines how flag changes roll out to environments, either as a `guarded-release`, which monitors the rollout against metrics with optional automatic rollback, or a `progressive-release`, which advances the rollout through a fixed schedule of allocation stages.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_launchdarkly as launchdarkly

        guarded_checkout = launchdarkly.ReleasePolicy("guarded_checkout",
            project_key=example["key"],
            key="guarded-checkout",
            name="Guarded checkout rollout",
            release_method="guarded-release",
            scope={
                "environment_keys": ["production"],
                "flag_tag_keys": ["checkout"],
            },
            guarded_release_config={
                "rollout_context_kind": "user",
                "min_sample_size": 1000,
                "rollback_on_regression": True,
                "metric_keys": [completed_purchase["key"]],
                "stages": [
                    {
                        "allocation": 10,
                        "duration_millis": 3600000,
                    },
                    {
                        "allocation": 50,
                        "duration_millis": 3600000,
                    },
                ],
            })
        progressive_rollout = launchdarkly.ReleasePolicy("progressive_rollout",
            project_key=example["key"],
            key="progressive-rollout",
            name="Progressive rollout",
            release_method="progressive-release",
            scope={
                "environment_keys": ["production"],
            },
            progressive_release_config={
                "rollout_context_kind": "user",
                "stages": [
                    {
                        "allocation": 20,
                        "duration_millis": 3600000,
                    },
                    {
                        "allocation": 60,
                        "duration_millis": 3600000,
                    },
                ],
            })
        ```

        ## Import

        A release policy can be imported using the project key and release policy key
        joined by a slash: project_key/release_policy_key.

        ```sh
        $ pulumi import launchdarkly:index/releasePolicy:ReleasePolicy guarded_checkout example-project/guarded-checkout
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['ReleasePolicyGuardedReleaseConfigArgs', 'ReleasePolicyGuardedReleaseConfigArgsDict']] guarded_release_config: Configuration for a `guarded-release`. May only be set when `release_method` is `guarded-release`.
        :param pulumi.Input[_builtins.str] key: The unique human-readable key that references the release policy. A change in this field forces the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.str] name: The human-friendly name for the release policy.
        :param pulumi.Input[Union['ReleasePolicyProgressiveReleaseConfigArgs', 'ReleasePolicyProgressiveReleaseConfigArgsDict']] progressive_release_config: Configuration for a `progressive-release`. May only be set when `release_method` is `progressive-release`.
        :param pulumi.Input[_builtins.str] project_key: The release policy's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.str] release_method: The release method this policy uses. Must be one of `guarded-release` or `progressive-release`. Set `guarded_release_config` for a `guarded-release` and `progressive_release_config` for a `progressive-release`.
        :param pulumi.Input[Union['ReleasePolicyScopeArgs', 'ReleasePolicyScopeArgsDict']] scope: The scope that determines which environments and flags this release policy applies to.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ReleasePolicyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Provides a LaunchDarkly release policy resource.

        > **Beta:** This resource wraps a beta LaunchDarkly API (the `release-policies` endpoints, accessed with the `LD-API-Version: beta` header). Beta resources may change or be removed in future versions.

        This resource lets you create and manage [release policies](https://launchdarkly.com/docs/home/releases/release-policies) within a LaunchDarkly project. A release policy defines how flag changes roll out to environments, either as a `guarded-release`, which monitors the rollout against metrics with optional automatic rollback, or a `progressive-release`, which advances the rollout through a fixed schedule of allocation stages.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_launchdarkly as launchdarkly

        guarded_checkout = launchdarkly.ReleasePolicy("guarded_checkout",
            project_key=example["key"],
            key="guarded-checkout",
            name="Guarded checkout rollout",
            release_method="guarded-release",
            scope={
                "environment_keys": ["production"],
                "flag_tag_keys": ["checkout"],
            },
            guarded_release_config={
                "rollout_context_kind": "user",
                "min_sample_size": 1000,
                "rollback_on_regression": True,
                "metric_keys": [completed_purchase["key"]],
                "stages": [
                    {
                        "allocation": 10,
                        "duration_millis": 3600000,
                    },
                    {
                        "allocation": 50,
                        "duration_millis": 3600000,
                    },
                ],
            })
        progressive_rollout = launchdarkly.ReleasePolicy("progressive_rollout",
            project_key=example["key"],
            key="progressive-rollout",
            name="Progressive rollout",
            release_method="progressive-release",
            scope={
                "environment_keys": ["production"],
            },
            progressive_release_config={
                "rollout_context_kind": "user",
                "stages": [
                    {
                        "allocation": 20,
                        "duration_millis": 3600000,
                    },
                    {
                        "allocation": 60,
                        "duration_millis": 3600000,
                    },
                ],
            })
        ```

        ## Import

        A release policy can be imported using the project key and release policy key
        joined by a slash: project_key/release_policy_key.

        ```sh
        $ pulumi import launchdarkly:index/releasePolicy:ReleasePolicy guarded_checkout example-project/guarded-checkout
        ```


        :param str resource_name: The name of the resource.
        :param ReleasePolicyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ReleasePolicyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 guarded_release_config: pulumi.Input[Optional[Union['ReleasePolicyGuardedReleaseConfigArgs', 'ReleasePolicyGuardedReleaseConfigArgsDict']]] = None,
                 key: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 progressive_release_config: pulumi.Input[Optional[Union['ReleasePolicyProgressiveReleaseConfigArgs', 'ReleasePolicyProgressiveReleaseConfigArgsDict']]] = None,
                 project_key: pulumi.Input[Optional[_builtins.str]] = None,
                 release_method: pulumi.Input[Optional[_builtins.str]] = None,
                 scope: pulumi.Input[Optional[Union['ReleasePolicyScopeArgs', 'ReleasePolicyScopeArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ReleasePolicyArgs.__new__(ReleasePolicyArgs)

            __props__.__dict__["guarded_release_config"] = guarded_release_config
            if key is None and not opts.urn:
                raise TypeError("Missing required property 'key'")
            __props__.__dict__["key"] = key
            __props__.__dict__["name"] = name
            __props__.__dict__["progressive_release_config"] = progressive_release_config
            if project_key is None and not opts.urn:
                raise TypeError("Missing required property 'project_key'")
            __props__.__dict__["project_key"] = project_key
            if release_method is None and not opts.urn:
                raise TypeError("Missing required property 'release_method'")
            __props__.__dict__["release_method"] = release_method
            __props__.__dict__["scope"] = scope
            __props__.__dict__["rank"] = None
        super(ReleasePolicy, __self__).__init__(
            'launchdarkly:index/releasePolicy:ReleasePolicy',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            guarded_release_config: pulumi.Input[Optional[Union['ReleasePolicyGuardedReleaseConfigArgs', 'ReleasePolicyGuardedReleaseConfigArgsDict']]] = None,
            key: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            progressive_release_config: pulumi.Input[Optional[Union['ReleasePolicyProgressiveReleaseConfigArgs', 'ReleasePolicyProgressiveReleaseConfigArgsDict']]] = None,
            project_key: pulumi.Input[Optional[_builtins.str]] = None,
            rank: pulumi.Input[Optional[_builtins.int]] = None,
            release_method: pulumi.Input[Optional[_builtins.str]] = None,
            scope: pulumi.Input[Optional[Union['ReleasePolicyScopeArgs', 'ReleasePolicyScopeArgsDict']]] = None) -> 'ReleasePolicy':
        """
        Get an existing ReleasePolicy resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['ReleasePolicyGuardedReleaseConfigArgs', 'ReleasePolicyGuardedReleaseConfigArgsDict']] guarded_release_config: Configuration for a `guarded-release`. May only be set when `release_method` is `guarded-release`.
        :param pulumi.Input[_builtins.str] key: The unique human-readable key that references the release policy. A change in this field forces the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.str] name: The human-friendly name for the release policy.
        :param pulumi.Input[Union['ReleasePolicyProgressiveReleaseConfigArgs', 'ReleasePolicyProgressiveReleaseConfigArgsDict']] progressive_release_config: Configuration for a `progressive-release`. May only be set when `release_method` is `progressive-release`.
        :param pulumi.Input[_builtins.str] project_key: The release policy's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
        :param pulumi.Input[_builtins.int] rank: The rank of the release policy within the project. LaunchDarkly assigns and orders the rank. Reorder release policies in the LaunchDarkly UI.
        :param pulumi.Input[_builtins.str] release_method: The release method this policy uses. Must be one of `guarded-release` or `progressive-release`. Set `guarded_release_config` for a `guarded-release` and `progressive_release_config` for a `progressive-release`.
        :param pulumi.Input[Union['ReleasePolicyScopeArgs', 'ReleasePolicyScopeArgsDict']] scope: The scope that determines which environments and flags this release policy applies to.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ReleasePolicyState.__new__(_ReleasePolicyState)

        __props__.__dict__["guarded_release_config"] = guarded_release_config
        __props__.__dict__["key"] = key
        __props__.__dict__["name"] = name
        __props__.__dict__["progressive_release_config"] = progressive_release_config
        __props__.__dict__["project_key"] = project_key
        __props__.__dict__["rank"] = rank
        __props__.__dict__["release_method"] = release_method
        __props__.__dict__["scope"] = scope
        return ReleasePolicy(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="guardedReleaseConfig")
    def guarded_release_config(self) -> pulumi.Output[Optional['outputs.ReleasePolicyGuardedReleaseConfig']]:
        """
        Configuration for a `guarded-release`. May only be set when `release_method` is `guarded-release`.
        """
        return pulumi.get(self, "guarded_release_config")

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Output[_builtins.str]:
        """
        The unique human-readable key that references the release policy. A change in this field forces the destruction of the existing resource and the creation of a new one.
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The human-friendly name for the release policy.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="progressiveReleaseConfig")
    def progressive_release_config(self) -> pulumi.Output[Optional['outputs.ReleasePolicyProgressiveReleaseConfig']]:
        """
        Configuration for a `progressive-release`. May only be set when `release_method` is `progressive-release`.
        """
        return pulumi.get(self, "progressive_release_config")

    @_builtins.property
    @pulumi.getter(name="projectKey")
    def project_key(self) -> pulumi.Output[_builtins.str]:
        """
        The release policy's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
        """
        return pulumi.get(self, "project_key")

    @_builtins.property
    @pulumi.getter
    def rank(self) -> pulumi.Output[_builtins.int]:
        """
        The rank of the release policy within the project. LaunchDarkly assigns and orders the rank. Reorder release policies in the LaunchDarkly UI.
        """
        return pulumi.get(self, "rank")

    @_builtins.property
    @pulumi.getter(name="releaseMethod")
    def release_method(self) -> pulumi.Output[_builtins.str]:
        """
        The release method this policy uses. Must be one of `guarded-release` or `progressive-release`. Set `guarded_release_config` for a `guarded-release` and `progressive_release_config` for a `progressive-release`.
        """
        return pulumi.get(self, "release_method")

    @_builtins.property
    @pulumi.getter
    def scope(self) -> pulumi.Output[Optional['outputs.ReleasePolicyScope']]:
        """
        The scope that determines which environments and flags this release policy applies to.
        """
        return pulumi.get(self, "scope")

