// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Launchdarkly.Outputs
{

    [OutputType]
    public sealed class GetProjectClientSideAvailabilityResult
    {
        public readonly bool? UsingEnvironmentId;
        public readonly bool? UsingMobileKey;

        [OutputConstructor]
        private GetProjectClientSideAvailabilityResult(
            bool? usingEnvironmentId,

            bool? usingMobileKey)
        {
            UsingEnvironmentId = usingEnvironmentId;
            UsingMobileKey = usingMobileKey;
        }
    }
}
