// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Launchdarkly.Outputs
{

    [OutputType]
    public sealed class SegmentIncludedContext
    {
        /// <summary>
        /// The context kind associated with this segment target. To target on user contexts, use the included and excluded attributes.
        /// </summary>
        public readonly string ContextKind;
        /// <summary>
        /// List of target object keys included in or excluded from the segment.
        /// </summary>
        public readonly ImmutableArray<string> Values;

        [OutputConstructor]
        private SegmentIncludedContext(
            string contextKind,

            ImmutableArray<string> values)
        {
            ContextKind = contextKind;
            Values = values;
        }
    }
}
