// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Launchdarkly.Inputs
{

    public sealed class FlagTemplatesBooleanDefaultsArgs : global::Pulumi.ResourceArgs
    {
        [Input("falseDescription", required: true)]
        public Input<string> FalseDescription { get; set; } = null!;

        [Input("falseDisplayName", required: true)]
        public Input<string> FalseDisplayName { get; set; } = null!;

        [Input("offVariation", required: true)]
        public Input<int> OffVariation { get; set; } = null!;

        [Input("onVariation", required: true)]
        public Input<int> OnVariation { get; set; } = null!;

        [Input("trueDescription", required: true)]
        public Input<string> TrueDescription { get; set; } = null!;

        [Input("trueDisplayName", required: true)]
        public Input<string> TrueDisplayName { get; set; } = null!;

        public FlagTemplatesBooleanDefaultsArgs()
        {
        }
        public static new FlagTemplatesBooleanDefaultsArgs Empty => new FlagTemplatesBooleanDefaultsArgs();
    }
}
