// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Launchdarkly.Inputs
{

    public sealed class ReleasePolicyScopeGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("environmentKeys")]
        private InputList<string>? _environmentKeys;

        /// <summary>
        /// The set of environment keys this policy applies to.
        /// </summary>
        public InputList<string> EnvironmentKeys
        {
            get => _environmentKeys ?? (_environmentKeys = new InputList<string>());
            set => _environmentKeys = value;
        }

        [Input("flagTagKeys")]
        private InputList<string>? _flagTagKeys;

        /// <summary>
        /// The set of flag tags this policy applies to.
        /// </summary>
        public InputList<string> FlagTagKeys
        {
            get => _flagTagKeys ?? (_flagTagKeys = new InputList<string>());
            set => _flagTagKeys = value;
        }

        public ReleasePolicyScopeGetArgs()
        {
        }
        public static new ReleasePolicyScopeGetArgs Empty => new ReleasePolicyScopeGetArgs();
    }
}
