// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Launchdarkly.Inputs
{

    public sealed class ReleasePolicyGuardedReleaseConfigStageArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The percentage of traffic (0-100) allocated to the new variation during this stage.
        /// </summary>
        [Input("allocation", required: true)]
        public Input<int> Allocation { get; set; } = null!;

        /// <summary>
        /// The duration of this stage, in milliseconds.
        /// </summary>
        [Input("durationMillis", required: true)]
        public Input<int> DurationMillis { get; set; } = null!;

        public ReleasePolicyGuardedReleaseConfigStageArgs()
        {
        }
        public static new ReleasePolicyGuardedReleaseConfigStageArgs Empty => new ReleasePolicyGuardedReleaseConfigStageArgs();
    }
}
