// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Launchdarkly.Inputs
{

    public sealed class ReleasePolicyProgressiveReleaseConfigGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The context kind key to use as the randomization unit for the rollout.
        /// </summary>
        [Input("rolloutContextKind")]
        public Input<string>? RolloutContextKind { get; set; }

        [Input("stages")]
        private InputList<Inputs.ReleasePolicyProgressiveReleaseConfigStageGetArgs>? _stages;

        /// <summary>
        /// An ordered list of rollout stages. Each stage advances the rollout to the given allocation for the given duration.
        /// </summary>
        public InputList<Inputs.ReleasePolicyProgressiveReleaseConfigStageGetArgs> Stages
        {
            get => _stages ?? (_stages = new InputList<Inputs.ReleasePolicyProgressiveReleaseConfigStageGetArgs>());
            set => _stages = value;
        }

        public ReleasePolicyProgressiveReleaseConfigGetArgs()
        {
        }
        public static new ReleasePolicyProgressiveReleaseConfigGetArgs Empty => new ReleasePolicyProgressiveReleaseConfigGetArgs();
    }
}
