// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides a LaunchDarkly AI tool data source.
 *
 * This data source allows you to retrieve AI tool information from your LaunchDarkly project.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as launchdarkly from "@pulumi/launchdarkly";
 *
 * const example = launchdarkly.getAiTool({
 *     key: "web-search",
 *     projectKey: "example-project",
 * });
 * ```
 */
export function getAiTool(args: GetAiToolArgs, opts?: pulumi.InvokeOptions): Promise<GetAiToolResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("launchdarkly:index/getAiTool:getAiTool", {
        "key": args.key,
        "projectKey": args.projectKey,
    }, opts);
}

/**
 * A collection of arguments for invoking getAiTool.
 */
export interface GetAiToolArgs {
    /**
     * The AI tool's unique key.
     */
    key: string;
    /**
     * The project key.
     */
    projectKey: string;
}

/**
 * A collection of values returned by getAiTool.
 */
export interface GetAiToolResult {
    /**
     * The creation timestamp of the AI tool.
     */
    readonly creationDate: number;
    /**
     * A JSON string representing custom application-level metadata for the AI tool.
     */
    readonly customParameters: string;
    /**
     * The AI tool's description.
     */
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The AI tool's unique key.
     */
    readonly key: string;
    /**
     * The member ID of the maintainer for this AI tool. Conflicts with `maintainerTeamKey`.
     */
    readonly maintainerId: string;
    /**
     * The team key of the maintainer team for this AI tool. Conflicts with `maintainerId`.
     */
    readonly maintainerTeamKey: string;
    /**
     * The project key.
     */
    readonly projectKey: string;
    /**
     * A JSON string representing the JSON Schema for the tool's parameters.
     */
    readonly schemaJson: string;
    /**
     * The version of the AI tool.
     */
    readonly version: number;
}
/**
 * Provides a LaunchDarkly AI tool data source.
 *
 * This data source allows you to retrieve AI tool information from your LaunchDarkly project.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as launchdarkly from "@pulumi/launchdarkly";
 *
 * const example = launchdarkly.getAiTool({
 *     key: "web-search",
 *     projectKey: "example-project",
 * });
 * ```
 */
export function getAiToolOutput(args: GetAiToolOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAiToolResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("launchdarkly:index/getAiTool:getAiTool", {
        "key": args.key,
        "projectKey": args.projectKey,
    }, opts);
}

/**
 * A collection of arguments for invoking getAiTool.
 */
export interface GetAiToolOutputArgs {
    /**
     * The AI tool's unique key.
     */
    key: pulumi.Input<string>;
    /**
     * The project key.
     */
    projectKey: pulumi.Input<string>;
}
