// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides a LaunchDarkly big segment store (persistent store) integration data source.
 *
 * > **Beta:** This data source wraps a beta LaunchDarkly API. Beta resources may change or be removed in future provider versions.
 *
 * This data source allows you to retrieve a persistent store integration configuration for an environment by its IDs.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as launchdarkly from "@pulumi/launchdarkly";
 *
 * const redisStore = launchdarkly.getBigSegmentStoreIntegration({
 *     projectKey: "example-project",
 *     environmentKey: "production",
 *     integrationKey: "redis",
 *     integrationId: "57c0a8e4f7b9c20b3c5d1234",
 * });
 * ```
 */
export function getBigSegmentStoreIntegration(args: GetBigSegmentStoreIntegrationArgs, opts?: pulumi.InvokeOptions): Promise<GetBigSegmentStoreIntegrationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("launchdarkly:index/getBigSegmentStoreIntegration:getBigSegmentStoreIntegration", {
        "environmentKey": args.environmentKey,
        "integrationId": args.integrationId,
        "integrationKey": args.integrationKey,
        "projectKey": args.projectKey,
    }, opts);
}

/**
 * A collection of arguments for invoking getBigSegmentStoreIntegration.
 */
export interface GetBigSegmentStoreIntegrationArgs {
    /**
     * The key of the environment the integration belongs to.
     */
    environmentKey: string;
    /**
     * The server-assigned ID of the integration configuration.
     */
    integrationId: string;
    /**
     * The persistent store technology. One of `redis` or `dynamodb`.
     */
    integrationKey: string;
    /**
     * The key of the project the integration belongs to.
     */
    projectKey: string;
}

/**
 * A collection of values returned by getBigSegmentStoreIntegration.
 */
export interface GetBigSegmentStoreIntegrationResult {
    /**
     * A JSON string holding the store-specific configuration. Marked sensitive because it carries credentials.
     */
    readonly config: string;
    /**
     * The key of the environment the integration belongs to.
     */
    readonly environmentKey: string;
    /**
     * The ID in the format `project_key/environment_key/integration_key/integration_id`.
     */
    readonly id: string;
    /**
     * The server-assigned ID of the integration configuration.
     */
    readonly integrationId: string;
    /**
     * The persistent store technology. One of `redis` or `dynamodb`.
     */
    readonly integrationKey: string;
    /**
     * A human-friendly name for the integration configuration.
     */
    readonly name: string;
    /**
     * Whether the integration is turned on.
     */
    readonly on: boolean;
    /**
     * The key of the project the integration belongs to.
     */
    readonly projectKey: string;
    /**
     * Tags associated with the integration configuration.
     */
    readonly tags: string[];
    /**
     * The version of the integration configuration.
     */
    readonly version: number;
}
/**
 * Provides a LaunchDarkly big segment store (persistent store) integration data source.
 *
 * > **Beta:** This data source wraps a beta LaunchDarkly API. Beta resources may change or be removed in future provider versions.
 *
 * This data source allows you to retrieve a persistent store integration configuration for an environment by its IDs.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as launchdarkly from "@pulumi/launchdarkly";
 *
 * const redisStore = launchdarkly.getBigSegmentStoreIntegration({
 *     projectKey: "example-project",
 *     environmentKey: "production",
 *     integrationKey: "redis",
 *     integrationId: "57c0a8e4f7b9c20b3c5d1234",
 * });
 * ```
 */
export function getBigSegmentStoreIntegrationOutput(args: GetBigSegmentStoreIntegrationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBigSegmentStoreIntegrationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("launchdarkly:index/getBigSegmentStoreIntegration:getBigSegmentStoreIntegration", {
        "environmentKey": args.environmentKey,
        "integrationId": args.integrationId,
        "integrationKey": args.integrationKey,
        "projectKey": args.projectKey,
    }, opts);
}

/**
 * A collection of arguments for invoking getBigSegmentStoreIntegration.
 */
export interface GetBigSegmentStoreIntegrationOutputArgs {
    /**
     * The key of the environment the integration belongs to.
     */
    environmentKey: pulumi.Input<string>;
    /**
     * The server-assigned ID of the integration configuration.
     */
    integrationId: pulumi.Input<string>;
    /**
     * The persistent store technology. One of `redis` or `dynamodb`.
     */
    integrationKey: pulumi.Input<string>;
    /**
     * The key of the project the integration belongs to.
     */
    projectKey: pulumi.Input<string>;
}
