// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * Provides a LaunchDarkly release policy data source.
 *
 * > **Beta:** This data source wraps a beta LaunchDarkly API (the `release-policies` endpoints, accessed with the `LD-API-Version: beta` header). Beta resources may change or be removed in future versions.
 *
 * This data source allows you to retrieve release policy information from your LaunchDarkly project.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as launchdarkly from "@pulumi/launchdarkly";
 *
 * const guardedCheckout = launchdarkly.getReleasePolicy({
 *     projectKey: "example-project",
 *     key: "guarded-checkout",
 * });
 * ```
 */
export function getReleasePolicy(args: GetReleasePolicyArgs, opts?: pulumi.InvokeOptions): Promise<GetReleasePolicyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("launchdarkly:index/getReleasePolicy:getReleasePolicy", {
        "key": args.key,
        "projectKey": args.projectKey,
    }, opts);
}

/**
 * A collection of arguments for invoking getReleasePolicy.
 */
export interface GetReleasePolicyArgs {
    /**
     * The unique human-readable key that references the release policy.
     */
    key: string;
    /**
     * The release policy's project key.
     */
    projectKey: string;
}

/**
 * A collection of values returned by getReleasePolicy.
 */
export interface GetReleasePolicyResult {
    /**
     * Configuration for a `guarded-release`.
     */
    readonly guardedReleaseConfig: outputs.GetReleasePolicyGuardedReleaseConfig;
    /**
     * The ID in the format `project_key/key`.
     */
    readonly id: string;
    /**
     * The unique human-readable key that references the release policy.
     */
    readonly key: string;
    /**
     * The human-friendly name for the release policy.
     */
    readonly name: string;
    /**
     * Configuration for a `progressive-release`.
     */
    readonly progressiveReleaseConfig: outputs.GetReleasePolicyProgressiveReleaseConfig;
    /**
     * The release policy's project key.
     */
    readonly projectKey: string;
    /**
     * The rank (priority) of the release policy within the project.
     */
    readonly rank: number;
    /**
     * The release method this policy uses. One of `guarded-release` or `progressive-release`.
     */
    readonly releaseMethod: string;
    /**
     * The scope that determines which environments and flags this release policy applies to.
     */
    readonly scope: outputs.GetReleasePolicyScope;
}
/**
 * Provides a LaunchDarkly release policy data source.
 *
 * > **Beta:** This data source wraps a beta LaunchDarkly API (the `release-policies` endpoints, accessed with the `LD-API-Version: beta` header). Beta resources may change or be removed in future versions.
 *
 * This data source allows you to retrieve release policy information from your LaunchDarkly project.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as launchdarkly from "@pulumi/launchdarkly";
 *
 * const guardedCheckout = launchdarkly.getReleasePolicy({
 *     projectKey: "example-project",
 *     key: "guarded-checkout",
 * });
 * ```
 */
export function getReleasePolicyOutput(args: GetReleasePolicyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetReleasePolicyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("launchdarkly:index/getReleasePolicy:getReleasePolicy", {
        "key": args.key,
        "projectKey": args.projectKey,
    }, opts);
}

/**
 * A collection of arguments for invoking getReleasePolicy.
 */
export interface GetReleasePolicyOutputArgs {
    /**
     * The unique human-readable key that references the release policy.
     */
    key: pulumi.Input<string>;
    /**
     * The release policy's project key.
     */
    projectKey: pulumi.Input<string>;
}
