// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides a LaunchDarkly team member data source.
 *
 * This data source allows you to retrieve team member information from your LaunchDarkly organization.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as launchdarkly from "@pulumi/launchdarkly";
 *
 * const example = launchdarkly.getTeamMember({
 *     email: "example@example.com",
 * });
 * ```
 */
export function getTeamMember(args: GetTeamMemberArgs, opts?: pulumi.InvokeOptions): Promise<GetTeamMemberResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("launchdarkly:index/getTeamMember:getTeamMember", {
        "email": args.email,
    }, opts);
}

/**
 * A collection of arguments for invoking getTeamMember.
 */
export interface GetTeamMemberArgs {
    /**
     * The unique email address associated with the team member.
     */
    email: string;
}

/**
 * A collection of values returned by getTeamMember.
 */
export interface GetTeamMemberResult {
    /**
     * The list of custom roles keys associated with the team member. Custom roles are only available to customers on an Enterprise plan. To learn more, [read about our pricing](https://launchdarkly.com/pricing/). To upgrade your plan, [contact LaunchDarkly Sales](https://launchdarkly.com/contact-sales/).
     */
    readonly customRoles: string[];
    /**
     * The unique email address associated with the team member.
     */
    readonly email: string;
    /**
     * First name.
     */
    readonly firstName: string;
    /**
     * The 24-character member ID.
     */
    readonly id: string;
    /**
     * Last name.
     */
    readonly lastName: string;
    /**
     * The role associated with the team member. Possible roles are `owner`, `reader`, `writer`, or `admin`.
     */
    readonly role: string;
    /**
     * A map of role attributes, keyed by the role attribute key with a string array of resource keys as each value. For example, if your policy statement defines the resource `"proj/$${roleAttribute/testAttribute}"`, the key would be `testAttribute` and the values the keys of the projects you wanted to assign access to.
     */
    readonly roleAttributes: {[key: string]: string[]};
}
/**
 * Provides a LaunchDarkly team member data source.
 *
 * This data source allows you to retrieve team member information from your LaunchDarkly organization.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as launchdarkly from "@pulumi/launchdarkly";
 *
 * const example = launchdarkly.getTeamMember({
 *     email: "example@example.com",
 * });
 * ```
 */
export function getTeamMemberOutput(args: GetTeamMemberOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTeamMemberResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("launchdarkly:index/getTeamMember:getTeamMember", {
        "email": args.email,
    }, opts);
}

/**
 * A collection of arguments for invoking getTeamMember.
 */
export interface GetTeamMemberOutputArgs {
    /**
     * The unique email address associated with the team member.
     */
    email: pulumi.Input<string>;
}
