// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides a LaunchDarkly IP allowlist configuration resource.
 *
 * > **Note:** IP allowlists are available to customers on an Enterprise LaunchDarkly plan. To learn more, [read about our pricing](https://launchdarkly.com/pricing/). To upgrade your plan, [contact LaunchDarkly Sales](https://launchdarkly.com/contact-sales/).
 *
 * > **Beta:** This resource uses a beta API. Beta resources may change or be removed in future versions.
 *
 * This resource allows you to manage the IP allowlist configuration for your LaunchDarkly account. There is only one configuration per account, so you should define only a single instance of this resource.
 */
export class IpAllowlistConfig extends pulumi.CustomResource {
    /**
     * Get an existing IpAllowlistConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IpAllowlistConfigState, opts?: pulumi.CustomResourceOptions): IpAllowlistConfig {
        return new IpAllowlistConfig(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'launchdarkly:index/ipAllowlistConfig:IpAllowlistConfig';

    /**
     * Returns true if the given object is an instance of IpAllowlistConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IpAllowlistConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IpAllowlistConfig.__pulumiType;
    }

    /**
     * Whether the scoped (API token) IP allowlist is enabled.
     */
    declare public readonly scopedAllowlistEnabled: pulumi.Output<boolean | undefined>;
    /**
     * Whether the session IP allowlist is enabled.
     */
    declare public readonly sessionAllowlistEnabled: pulumi.Output<boolean | undefined>;

    /**
     * Create a IpAllowlistConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IpAllowlistConfigArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IpAllowlistConfigArgs | IpAllowlistConfigState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IpAllowlistConfigState | undefined;
            resourceInputs["scopedAllowlistEnabled"] = state?.scopedAllowlistEnabled;
            resourceInputs["sessionAllowlistEnabled"] = state?.sessionAllowlistEnabled;
        } else {
            const args = argsOrState as IpAllowlistConfigArgs | undefined;
            resourceInputs["scopedAllowlistEnabled"] = args?.scopedAllowlistEnabled;
            resourceInputs["sessionAllowlistEnabled"] = args?.sessionAllowlistEnabled;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IpAllowlistConfig.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IpAllowlistConfig resources.
 */
export interface IpAllowlistConfigState {
    /**
     * Whether the scoped (API token) IP allowlist is enabled.
     */
    scopedAllowlistEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the session IP allowlist is enabled.
     */
    sessionAllowlistEnabled?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a IpAllowlistConfig resource.
 */
export interface IpAllowlistConfigArgs {
    /**
     * Whether the scoped (API token) IP allowlist is enabled.
     */
    scopedAllowlistEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the session IP allowlist is enabled.
     */
    sessionAllowlistEnabled?: pulumi.Input<boolean | undefined>;
}
