// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the launchdarkly package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'launchdarkly';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * The [personal access token](https://docs.launchdarkly.com/home/account-security/api-access-tokens#personal-tokens) or
     * [service token](https://docs.launchdarkly.com/home/account-security/api-access-tokens#service-tokens) used to
     * authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_ACCESS_TOKEN` environment variable. You
     * must provide either `accessToken` or `oauthToken`.
     */
    public readonly accessToken!: pulumi.Output<string | undefined>;
    /**
     * The LaunchDarkly host address. If this argument is not specified, the default host address is
     * `https://app.launchdarkly.com`
     */
    public readonly apiHost!: pulumi.Output<string | undefined>;
    /**
     * An OAuth V2 token you use to authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_OAUTH_TOKEN`
     * environment variable. You must provide either `accessToken` or `oauthToken`.
     */
    public readonly oauthToken!: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["accessToken"] = args ? args.accessToken : undefined;
            resourceInputs["apiHost"] = args ? args.apiHost : undefined;
            resourceInputs["httpTimeout"] = pulumi.output(args ? args.httpTimeout : undefined).apply(JSON.stringify);
            resourceInputs["oauthToken"] = args ? args.oauthToken : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * The [personal access token](https://docs.launchdarkly.com/home/account-security/api-access-tokens#personal-tokens) or
     * [service token](https://docs.launchdarkly.com/home/account-security/api-access-tokens#service-tokens) used to
     * authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_ACCESS_TOKEN` environment variable. You
     * must provide either `accessToken` or `oauthToken`.
     */
    accessToken?: pulumi.Input<string>;
    /**
     * The LaunchDarkly host address. If this argument is not specified, the default host address is
     * `https://app.launchdarkly.com`
     */
    apiHost?: pulumi.Input<string>;
    /**
     * The HTTP timeout (in seconds) when making API calls to LaunchDarkly.
     */
    httpTimeout?: pulumi.Input<number>;
    /**
     * An OAuth V2 token you use to authenticate with LaunchDarkly. You can also set this with the `LAUNCHDARKLY_OAUTH_TOKEN`
     * environment variable. You must provide either `accessToken` or `oauthToken`.
     */
    oauthToken?: pulumi.Input<string>;
}
