// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * Provides a LaunchDarkly segment resource.
 *
 * This resource allows you to create and manage segments within your LaunchDarkly organization.
 *
 * > **Note:** When [segment approvals](https://launchdarkly.com/docs/home/releases/approvals) are enabled for an environment, segment **targeting** changes (`included`, `excluded`, `rules`, `includedContexts`, `excludedContexts`) require approval. To let pulumi up these changes non-interactively, grant its access token a custom role (`launchdarkly.CustomRole`) that includes the `bypassRequiredSegmentApproval` action. Without that permission, `pulumi up` fails with an "approval is required" error. In that case, manage targeting through the approval workflow, for example with `lifecycle { ignoreChanges = [included, excluded, rules] }`, disable segment approvals for the environment, or switch to a token that has the bypass permission. A segment with no targeting can be created and managed regardless.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as launchdarkly from "@pulumi/launchdarkly";
 *
 * // This example shows the use of tags, targets, context targets, and rules for a segment
 * const example = new launchdarkly.Segment("example", {
 *     key: "example-segment-key",
 *     projectKey: exampleLaunchdarklyProject.key,
 *     envKey: exampleLaunchdarklyEnvironment.key,
 *     name: "example segment",
 *     description: "This segment is managed by Terraform",
 *     tags: [
 *         "segment-tag-1",
 *         "segment-tag-2",
 *     ],
 *     includeds: [
 *         "user1",
 *         "user2",
 *     ],
 *     excludeds: [
 *         "user3",
 *         "user4",
 *     ],
 *     includedContexts: [{
 *         values: [
 *             "account1",
 *             "account2",
 *         ],
 *         context_kind: "account",
 *     }],
 *     rules: [{
 *         clauses: [{
 *             attribute: "country",
 *             op: "startsWith",
 *             values: [
 *                 "en",
 *                 "de",
 *                 "un",
 *             ],
 *             negate: false,
 *             contextKind: "location-data",
 *         }],
 *     }],
 * });
 * // This example shows a segment configured to have an unbounded number of individual targets
 * const big_example = new launchdarkly.Segment("big-example", {
 *     key: "example-big-segment-key",
 *     projectKey: exampleLaunchdarklyProject.key,
 *     envKey: exampleLaunchdarklyEnvironment.key,
 *     name: "example big segment",
 *     description: "This big segment is managed by Terraform",
 *     tags: [
 *         "segment-tag-1",
 *         "segment-tag-2",
 *     ],
 *     unbounded: true,
 *     unboundedContextKind: "user",
 * });
 * // This example shows a segment with a targeting rule that uses all clause operators
 * const segmentWithAllClauseOperators = new launchdarkly.Segment("segment_with_all_clause_operators", {
 *     name: "Segment with all clause operators",
 *     key: "segment-operators",
 *     projectKey: "projectx",
 *     envKey: "development",
 *     rules: [{
 *         clauses: [
 *             {
 *                 attribute: "username",
 *                 op: "in",
 *                 values: [
 *                     "henrietta powell",
 *                     "wally waterbear",
 *                 ],
 *             },
 *             {
 *                 attribute: "username",
 *                 op: "endsWith",
 *                 values: [
 *                     "powell",
 *                     "waterbear",
 *                 ],
 *             },
 *             {
 *                 attribute: "username",
 *                 op: "startsWith",
 *                 values: [
 *                     "henrietta",
 *                     "wally",
 *                 ],
 *             },
 *             {
 *                 attribute: "username",
 *                 op: "matches",
 *                 values: ["henr*"],
 *             },
 *             {
 *                 attribute: "username",
 *                 op: "contains",
 *                 values: ["water"],
 *             },
 *             {
 *                 attribute: "pageVisits",
 *                 op: "lessThan",
 *                 values: ["100"],
 *             },
 *             {
 *                 attribute: "pageVisits",
 *                 op: "lessThanOrEqual",
 *                 values: ["100"],
 *             },
 *             {
 *                 attribute: "pageVisits",
 *                 op: "greaterThan",
 *                 values: ["100"],
 *             },
 *             {
 *                 attribute: "pageVisits",
 *                 op: "greaterThanOrEqual",
 *                 values: ["100"],
 *             },
 *             {
 *                 attribute: "creationDate",
 *                 op: "before",
 *                 values: ["2024-05-03T15:57:30Z"],
 *             },
 *             {
 *                 attribute: "creationDate",
 *                 op: "after",
 *                 values: ["2024-05-03T15:57:30Z"],
 *             },
 *             {
 *                 attribute: "version",
 *                 op: "semVerEqual",
 *                 values: [
 *                     "1.0.0",
 *                     "1.0.1",
 *                 ],
 *                 contextKind: "application",
 *             },
 *             {
 *                 attribute: "version",
 *                 op: "semVerLessThan",
 *                 values: ["1.0.0"],
 *                 contextKind: "application",
 *             },
 *             {
 *                 attribute: "version",
 *                 op: "semVerGreaterThan",
 *                 values: ["1.0.0"],
 *                 contextKind: "application",
 *             },
 *             {
 *                 attribute: "context",
 *                 op: "segmentMatch",
 *                 values: ["test-segment"],
 *             },
 *         ],
 *     }],
 * });
 * // Example: Segment with view associations
 * // This approach is ideal for modular Terraform where each segment is managed in its own file
 * //
 * // Always reference the view rather than repeating its key as a string literal.
 * // A view must exist before Terraform can link a segment to it, and Terraform only
 * // knows to create the view first if the segment references it. With a string
 * // literal there is no dependency between the two resources, so Terraform can
 * // create the segment first and the apply fails with "view does not exist".
 * // Referencing the view also rules out a mistyped key.
 * const salesTeam = new launchdarkly.View("sales_team", {
 *     projectKey: "example-project",
 *     key: "sales-team",
 *     name: "Sales Team",
 *     maintainerTeamKey: "sales",
 * });
 * const customerSuccess = new launchdarkly.View("customer_success", {
 *     projectKey: "example-project",
 *     key: "customer-success",
 *     name: "Customer Success",
 *     maintainerTeamKey: "customer-success",
 * });
 * const premiumUsers = new launchdarkly.Segment("premium_users", {
 *     key: "premium-users",
 *     projectKey: "example-project",
 *     envKey: "production",
 *     name: "Premium Users",
 *     description: "Users with premium subscriptions",
 *     viewKeys: [
 *         salesTeam.key,
 *         customerSuccess.key,
 *     ],
 *     tags: [
 *         "premium",
 *         "subscription",
 *     ],
 *     rules: [{
 *         clauses: [{
 *             attribute: "plan",
 *             op: "in",
 *             values: [
 *                 "premium",
 *                 "enterprise",
 *             ],
 *         }],
 *     }],
 * });
 * // Example: Segment managed in a module that can specify its own views
 * // This enables a modular structure where each team/domain can manage their segments
 * // without needing to coordinate with a central view_links resource
 * //
 * // When the view is owned by another configuration or state (for example a
 * // platform team's workspace), use the data source. This asserts the view already
 * // exists, so a typo or a missing view fails during plan instead of mid-apply.
 * const productTeam = launchdarkly.getView({
 *     projectKey: "example-project",
 *     key: "product-team",
 * });
 * const betaTesters = new launchdarkly.Segment("beta_testers", {
 *     key: "beta-testers",
 *     projectKey: "example-project",
 *     envKey: "staging",
 *     name: "Beta Testers",
 *     viewKeys: [productTeam.then(productTeam => productTeam.key)],
 *     tags: [
 *         "beta",
 *         "testing",
 *     ],
 *     includeds: [
 *         "user123",
 *         "user456",
 *     ],
 * });
 * ```
 *
 * ## Import
 *
 * LaunchDarkly segments can be imported using the segment's ID in the form `project_key/env_key/segment_key`
 *
 * ```sh
 * $ pulumi import launchdarkly:index/segment:Segment example example-project/example-environment/example-segment-key
 * ```
 */
export class Segment extends pulumi.CustomResource {
    /**
     * Get an existing Segment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SegmentState, opts?: pulumi.CustomResourceOptions): Segment {
        return new Segment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'launchdarkly:index/segment:Segment';

    /**
     * Returns true if the given object is an instance of Segment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Segment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Segment.__pulumiType;
    }

    /**
     * The segment's creation date represented as a UNIX epoch timestamp.
     */
    declare public /*out*/ readonly creationDate: pulumi.Output<number>;
    /**
     * The description of the segment's purpose.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The segment's environment key. A change in this field forces the destruction of the existing resource and the creation of a new one.
     */
    declare public readonly envKey: pulumi.Output<string>;
    /**
     * List of non-user target objects excluded from the segment. This attribute is not valid when `unbounded` is set to `true`.
     */
    declare public readonly excludedContexts: pulumi.Output<outputs.SegmentExcludedContext[] | undefined>;
    /**
     * List of user keys excluded from the segment. To target on other context kinds, use the excludedContexts block attribute. This attribute is not valid when `unbounded` is set to `true`.
     */
    declare public readonly excludeds: pulumi.Output<string[] | undefined>;
    /**
     * List of non-user target objects included in the segment. This attribute is not valid when `unbounded` is set to `true`.
     */
    declare public readonly includedContexts: pulumi.Output<outputs.SegmentIncludedContext[] | undefined>;
    /**
     * List of user keys included in the segment. To target on other context kinds, use the includedContexts block attribute. This attribute is not valid when `unbounded` is set to `true`.
     */
    declare public readonly includeds: pulumi.Output<string[] | undefined>;
    /**
     * The unique key that references the segment. A change in this field forces the destruction of the existing resource and the creation of a new one.
     */
    declare public readonly key: pulumi.Output<string>;
    /**
     * The human-friendly name for the segment.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The segment's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
     */
    declare public readonly projectKey: pulumi.Output<string>;
    /**
     * List of custom rules to apply to the segment. This attribute is not valid when `unbounded` is set to `true`.
     */
    declare public readonly rules: pulumi.Output<outputs.SegmentRule[] | undefined>;
    /**
     * Tags associated with your resource.
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    /**
     * Whether to create a standard segment (`false`) or a big segment (`true`). Standard segments include rule-based and smaller list-based segments. Big segments include larger list-based segments and synced segments. Only use a big segment if you need to add more than 15,000 individual targets. It is not possible to manage the list of targeted contexts for big segments with Terraform. A change in this field forces the destruction of the existing resource and the creation of a new one.
     */
    declare public readonly unbounded: pulumi.Output<boolean>;
    /**
     * For big segments, the targeted context kind. If this attribute is not specified it defaults to `user`. A change in this field forces the destruction of the existing resource and the creation of a new one.
     */
    declare public readonly unboundedContextKind: pulumi.Output<string>;
    /**
     * A set of view keys to link this segment to. This is an alternative to using the `launchdarkly.ViewLinks` resource for managing view associations. When set, this segment is linked to the specified views. Reference the view rather than repeating its key as a string literal. For example, use `viewKeys = [launchdarkly_view.my_view.key]`, or `[data.launchdarkly_view.my_view.key]` when another configuration owns the view. A view must exist before Terraform can link a segment to it, and that reference is what tells Terraform to create the view first. The field is also computed, so Terraform reads back the current view associations from LaunchDarkly to detect drift. To explicitly remove all view associations, set `viewKeys = []`. Removing the field from your configuration leaves existing associations unchanged. **Important**: Avoid using both `viewKeys` and `launchdarkly.ViewLinks` to manage the same segment. Mixed ownership can cause conflicts. When Terraform detects them, it logs a warning and reconciles to the configured `viewKeys`. Choose one approach per resource.
     */
    declare public readonly viewKeys: pulumi.Output<string[]>;

    /**
     * Create a Segment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SegmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SegmentArgs | SegmentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SegmentState | undefined;
            resourceInputs["creationDate"] = state?.creationDate;
            resourceInputs["description"] = state?.description;
            resourceInputs["envKey"] = state?.envKey;
            resourceInputs["excludedContexts"] = state?.excludedContexts;
            resourceInputs["excludeds"] = state?.excludeds;
            resourceInputs["includedContexts"] = state?.includedContexts;
            resourceInputs["includeds"] = state?.includeds;
            resourceInputs["key"] = state?.key;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectKey"] = state?.projectKey;
            resourceInputs["rules"] = state?.rules;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["unbounded"] = state?.unbounded;
            resourceInputs["unboundedContextKind"] = state?.unboundedContextKind;
            resourceInputs["viewKeys"] = state?.viewKeys;
        } else {
            const args = argsOrState as SegmentArgs | undefined;
            if (args?.envKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'envKey'");
            }
            if (args?.key === undefined && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if (args?.projectKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectKey'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["envKey"] = args?.envKey;
            resourceInputs["excludedContexts"] = args?.excludedContexts;
            resourceInputs["excludeds"] = args?.excludeds;
            resourceInputs["includedContexts"] = args?.includedContexts;
            resourceInputs["includeds"] = args?.includeds;
            resourceInputs["key"] = args?.key;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectKey"] = args?.projectKey;
            resourceInputs["rules"] = args?.rules;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["unbounded"] = args?.unbounded;
            resourceInputs["unboundedContextKind"] = args?.unboundedContextKind;
            resourceInputs["viewKeys"] = args?.viewKeys;
            resourceInputs["creationDate"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Segment.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Segment resources.
 */
export interface SegmentState {
    /**
     * The segment's creation date represented as a UNIX epoch timestamp.
     */
    creationDate?: pulumi.Input<number | undefined>;
    /**
     * The description of the segment's purpose.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The segment's environment key. A change in this field forces the destruction of the existing resource and the creation of a new one.
     */
    envKey?: pulumi.Input<string | undefined>;
    /**
     * List of non-user target objects excluded from the segment. This attribute is not valid when `unbounded` is set to `true`.
     */
    excludedContexts?: pulumi.Input<pulumi.Input<inputs.SegmentExcludedContext>[] | undefined>;
    /**
     * List of user keys excluded from the segment. To target on other context kinds, use the excludedContexts block attribute. This attribute is not valid when `unbounded` is set to `true`.
     */
    excludeds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * List of non-user target objects included in the segment. This attribute is not valid when `unbounded` is set to `true`.
     */
    includedContexts?: pulumi.Input<pulumi.Input<inputs.SegmentIncludedContext>[] | undefined>;
    /**
     * List of user keys included in the segment. To target on other context kinds, use the includedContexts block attribute. This attribute is not valid when `unbounded` is set to `true`.
     */
    includeds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The unique key that references the segment. A change in this field forces the destruction of the existing resource and the creation of a new one.
     */
    key?: pulumi.Input<string | undefined>;
    /**
     * The human-friendly name for the segment.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The segment's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
     */
    projectKey?: pulumi.Input<string | undefined>;
    /**
     * List of custom rules to apply to the segment. This attribute is not valid when `unbounded` is set to `true`.
     */
    rules?: pulumi.Input<pulumi.Input<inputs.SegmentRule>[] | undefined>;
    /**
     * Tags associated with your resource.
     */
    tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether to create a standard segment (`false`) or a big segment (`true`). Standard segments include rule-based and smaller list-based segments. Big segments include larger list-based segments and synced segments. Only use a big segment if you need to add more than 15,000 individual targets. It is not possible to manage the list of targeted contexts for big segments with Terraform. A change in this field forces the destruction of the existing resource and the creation of a new one.
     */
    unbounded?: pulumi.Input<boolean | undefined>;
    /**
     * For big segments, the targeted context kind. If this attribute is not specified it defaults to `user`. A change in this field forces the destruction of the existing resource and the creation of a new one.
     */
    unboundedContextKind?: pulumi.Input<string | undefined>;
    /**
     * A set of view keys to link this segment to. This is an alternative to using the `launchdarkly.ViewLinks` resource for managing view associations. When set, this segment is linked to the specified views. Reference the view rather than repeating its key as a string literal. For example, use `viewKeys = [launchdarkly_view.my_view.key]`, or `[data.launchdarkly_view.my_view.key]` when another configuration owns the view. A view must exist before Terraform can link a segment to it, and that reference is what tells Terraform to create the view first. The field is also computed, so Terraform reads back the current view associations from LaunchDarkly to detect drift. To explicitly remove all view associations, set `viewKeys = []`. Removing the field from your configuration leaves existing associations unchanged. **Important**: Avoid using both `viewKeys` and `launchdarkly.ViewLinks` to manage the same segment. Mixed ownership can cause conflicts. When Terraform detects them, it logs a warning and reconciles to the configured `viewKeys`. Choose one approach per resource.
     */
    viewKeys?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a Segment resource.
 */
export interface SegmentArgs {
    /**
     * The description of the segment's purpose.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The segment's environment key. A change in this field forces the destruction of the existing resource and the creation of a new one.
     */
    envKey: pulumi.Input<string>;
    /**
     * List of non-user target objects excluded from the segment. This attribute is not valid when `unbounded` is set to `true`.
     */
    excludedContexts?: pulumi.Input<pulumi.Input<inputs.SegmentExcludedContext>[] | undefined>;
    /**
     * List of user keys excluded from the segment. To target on other context kinds, use the excludedContexts block attribute. This attribute is not valid when `unbounded` is set to `true`.
     */
    excludeds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * List of non-user target objects included in the segment. This attribute is not valid when `unbounded` is set to `true`.
     */
    includedContexts?: pulumi.Input<pulumi.Input<inputs.SegmentIncludedContext>[] | undefined>;
    /**
     * List of user keys included in the segment. To target on other context kinds, use the includedContexts block attribute. This attribute is not valid when `unbounded` is set to `true`.
     */
    includeds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The unique key that references the segment. A change in this field forces the destruction of the existing resource and the creation of a new one.
     */
    key: pulumi.Input<string>;
    /**
     * The human-friendly name for the segment.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The segment's project key. A change in this field forces the destruction of the existing resource and the creation of a new one.
     */
    projectKey: pulumi.Input<string>;
    /**
     * List of custom rules to apply to the segment. This attribute is not valid when `unbounded` is set to `true`.
     */
    rules?: pulumi.Input<pulumi.Input<inputs.SegmentRule>[] | undefined>;
    /**
     * Tags associated with your resource.
     */
    tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether to create a standard segment (`false`) or a big segment (`true`). Standard segments include rule-based and smaller list-based segments. Big segments include larger list-based segments and synced segments. Only use a big segment if you need to add more than 15,000 individual targets. It is not possible to manage the list of targeted contexts for big segments with Terraform. A change in this field forces the destruction of the existing resource and the creation of a new one.
     */
    unbounded?: pulumi.Input<boolean | undefined>;
    /**
     * For big segments, the targeted context kind. If this attribute is not specified it defaults to `user`. A change in this field forces the destruction of the existing resource and the creation of a new one.
     */
    unboundedContextKind?: pulumi.Input<string | undefined>;
    /**
     * A set of view keys to link this segment to. This is an alternative to using the `launchdarkly.ViewLinks` resource for managing view associations. When set, this segment is linked to the specified views. Reference the view rather than repeating its key as a string literal. For example, use `viewKeys = [launchdarkly_view.my_view.key]`, or `[data.launchdarkly_view.my_view.key]` when another configuration owns the view. A view must exist before Terraform can link a segment to it, and that reference is what tells Terraform to create the view first. The field is also computed, so Terraform reads back the current view associations from LaunchDarkly to detect drift. To explicitly remove all view associations, set `viewKeys = []`. Removing the field from your configuration leaves existing associations unchanged. **Important**: Avoid using both `viewKeys` and `launchdarkly.ViewLinks` to manage the same segment. Mixed ownership can cause conflicts. When Terraform detects them, it logs a warning and reconciles to the configured `viewKeys`. Choose one approach per resource.
     */
    viewKeys?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
